deploy/mac_osx/README.md

The current OSX project loading instructions reference old file paths. If we update to use `load_project_dir` instead of the old add_* commands, issues are fixed!

Use load_project_dir in OSX README

---

deploy/mac_osx/xbrowse_settings/local_settings.py
xbrowse/annotation/annotator.py
xbrowse_server/base/management/commands/load_resources.py

The changes here make CustomAnnotator optional, so the macos install can install with a smaller footprint. 
Basically, you can use only the basic annotations from VEP if you use: 
CUSTOM_ANNOTATOR_SETTINGS=None
in local_settings.py. 
The changes here shouldn't affect anything in production - if CUSTOM_ANNOTATOR_SETTINGS is set - unless you are using the files in `deploy/mac_osx/xbrowse_settings` somewhere else.

Making custom annotator optional again

---

xbrowse_server/analysis/diagnostic_search.py
xbrowse_server/analysis/family_group.py
xbrowse_server/analysis/project.py
xbrowse_server/api/utils.py
xbrowse_server/api/views.py
xbrowse_server/base/lookups.py
xbrowse_server/base/management/commands/batch_family_fileset.py
xbrowse_server/base/management/commands/check_for_missing_variants.py
xbrowse_server/base/management/commands/generate_variant_report.py
xbrowse_server/base/management/commands/reload_family.py
xbrowse_server/base/models.py
xbrowse_server/base/views/family_views.py
xbrowse_server/mall.py
xbrowse_server/sample_management.py
xbrowse_server/xbrowse_controls.py

This allows you to use a second MongoDatastore from a different database connection, for select projects. To enable, add the following lines to local_settings.py: 
SECONDARY_DATASTORE_PROJECTS = [
'1kg2'
]
SECONDARY_DATASTORE_PORT =  27018
_secondary_conn = pymongo.Connection(port=SECONDARY_DATASTORE_PORT)
SECONDARY_DATASTORE_DB = _secondary_conn['xbrowse_datastore']
SECONDARY_POPULATION_DATASTORE_DB = _secondary_conn['xbrowse_pop_datastore']
Then, if you run a second `mongod` on port 27018, the second mongo will be used for project `1kg2`. 
Important: you must add '1kg2' to `SECONDARY_DATASTORE_PROJECTS` *before* yo load any of its data. 
Here's how to replicate this locally on your mac install: 
0. Run a new mongodb: 
mongod --dbpath [new db path] --storageEngine wiredTiger --port 27018 …

Adding support for secondary datastore

---

test/annotation/test_vep_annotations.py
xbrowse/annotation/vep_annotations.py
xbrowse_server/base/management/commands/generate_variant_report.py

For a given variant, if some of the VEP-annotated transcripts are protein coding, then ignore the non-protein-coding transcripts when chosing the worst-affected transcript

Fix for transcript choice of CAPN3 vs. RP11-164J13.1

---

xbrowse_server/base/management/commands/migrate_analysis_status.py
xbrowse_server/base/models.py
xbrowse_server/base/views/family_views.py
xbrowse_server/json_displays.py
xbrowse_server/templates/family/family_home.html

realized that for one-to-one relationships such as between Family and AnalsyisStatus, it's simpler to add fields to the Family model than to create a separate AnalysisStatus table where records need to be created/deleted in sync with Family records, so moving the analysis_status date_saved and saved_by fields into the Family model

reimplemented analysis status tracking

---

xbrowse_server/base/management/commands/set_bam_paths.py

The current set_bam_paths command checks that both the BAM file and the index file for the BAM file exist when an http BAM file path is set for use with Readviz. However it assumes the index has only the ".bai" suffix and not the ".bam.bai" suffix which is commonly used. This change allows for BAM files to have ".bam.bai" suffixes when setting their paths for read visualization.

Alternate bam index url format

---

deploy/README.md
deploy/mac_osx/README.md

In the README for deployment, the link to the dbNSFP plugin actually
pointed to the LoFTEE plugin.

Fix link to wrong plugin

---

xbrowse_server/api/views.py
xbrowse_server/templates/reports/project_report.html

The "MME submitted families table" is used to see what families in a project are in MME. The API endpoints were fine, and the problem was with the UI. Updated it to take out some fields that were not used but introduced instability since the data behind them was not always available or standard

Hotfix mme submission report fix

---

xbrowse_server/base/utils.py

We had a user getting 500 errors when trying to load the genesearch page, it turns out that this is a real bug but you only see it if you have no available mongo projects so we missed it

Fix gene search for users with few projects

---

xbrowse_server/templates/matchmaker/matchmaker_search_page.html

-making the Broad CMG contact name in the submission dialing not-editable
-making the Broad CMG contact email in the submission dialing not-editable
-making the "no" phenotypes in submission dialog red color for visibility 
-making the phenotypes table in submission dialog sortable
-refactoring and other bug fixes such as removing trailing commas in name adjustments in input dialogs (submission dialog)

Feature not allow matchmaker addr tobe edited

---

deploy/docker/matchbox/Dockerfile

Updating the Exomiser version and the reference dataset used by it in the seqr Dockerfile. Put in the new reference data to the google bucket and pointed this Dockerfile to it. Local tests work fine

Updating the Exomiser version and the reference dataset used by it in

---

xbrowse_server/base/views/project_views.py

If a variant exists in multiple indices in gene search we were essentially just using the genotypes from the final index instead of all of them, because for individuals absent in an index we assign them a genotype with num_alt -1

Fix gene search genotypes

---

deploy/servctl_utils/deploy_command_utils.py

This allows us to either use the service account key in the deployed secrets so our seqr instance can have access to our private buckets, or it will default to the account credentials that allow local installs access to our reference data

Allow secret service account key

---

xbrowse_server/templates/client_templates/basic_variant.html

This PR fixes problem with Variant Search feature.
Steps to reproduce:
* Go to any project
* Select sample with loaded dataset
* Go to Variant Search
* Select search method: "All Variants" and any severity, click "Search".
Expected behaviour:
List of variants is displayed.
Observed behaviour:
Throbber is displayed, no variants appear, error message is logged to JavaScript console:
```
VM1419:413 Uncaught TypeError: Cannot read property 'split' of undefined
at r.eval (eval at w.template (underscore-min.js:1), <anonymous>:413:82)
at r.c [as template] (underscore-min.js:1)
at render (basic_variant.js:41)
at basic_variants_table.js:44
at Array.forEach (<anonymous>)
at Function.w.each.w.forEach (underscore-min.js:1)
at render (basic_variants_table.js:30)
at render …
```

Variant Searching does not display any results

---

reference_data/migrations/0013_auto_20190404_1953.py

Steps to reproduce:
* Create PostgreSQL database
* Restore from https://storage.googleapis.com/seqr-reference-data/gene_reference_data_backup.gz
* Apply migrations: "python manage.py migrate"
Observed behavior:
Migration reference_data.0013_auto_20190404_1953 fails with error:
```
Migrations for 'reference_data':
reference_data/migrations/0015_auto_20190411_1329.py
- Alter field expression_values on geneexpression
Operations to perform:
Apply all migrations: admin, auth, base, breakpoint_search, contenttypes, gene_lists, guardian, reference_data, seqr, sessions
Running migrations:
Applying base.0055_auto_20181106_1855... OK
Applying base.0056_auto_20190410_1453... OK
Applying reference_data.0010_auto_20190319_1518... OK
Applying reference_data.0011_primateai... OK
Applying …
```

Migration "reference_data.0013_auto_20190404_1953" fails

---

ui/shared/components/panel/view-pedigree-image/PedigreeImagePanel.jsx

Increase the size of the pedigree image in inheritance search to display larger labels in the images.

increase size of pedigree image in inheritance search

---

seqr/management/commands/check_bam_cram_paths.py
seqr/management/commands/check_bam_cram_paths_tests.py

Two tests have been added. One is normal test while another is for exception test.
A change: BytesIO is used instead of StringIO because stdout is written with a str rather than a unicode (if a unicode is provided then it is casted to str). 
The check_bam_cram_paths implementation must replace print() with self.stdout.write() according to https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/

Added unit test for check_bam_cram_paths command.

---

seqr/management/commands/reset_cached_search_results.py
seqr/management/commands/reset_cached_search_results_tests.py

Added unit tests for the reset_cached_search_results command and fixed a unicode issue in the command code.

Seqr manage command reset_cached_search_results unit test

---

seqr/fixtures/1kg_project.json
seqr/management/commands/lift_project_to_hg38.py
seqr/management/commands/lift_project_to_hg38_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/test_utils.py

Added a test for the basic features of lift_project_to_hg38. Exception tests are not included.
The lift_project_to_hg38.py was modified to fixed a unicode issue and a argument mismatch issue of the _update_variant_samples() method.

Seqr management command lift_project_to_hg38 unit test

---

seqr/utils/elasticsearch/utils.py
settings.py

Resubmit of PR https://github.com/macarthur-lab/seqr/pull/1254
I found that even if I set ELASTICSEARCH_PORT in the django settings.py, SeqR would still try to query on port 9200. I tracked it down to the ElasticSearch constructor, which only uses the hostname and doesn't pass the port through. This change corrected the problem for me.

fix failure to use custom configured ES port

---

seqr/management/tests/reload_saved_variant_json_tests.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/variant_utils.py

Due to the way a utility function was mocked out and the inputs to the mocked calls were never properly tested, the functionality for reloading variants has been broken for a while. This fixes and refactors that code, and increases the test coverage so it won't happen again
Reloading saved variants happens in the background when a dataset is updated, and as such it will fail silently and not have much of a noticeable effect when broken, which is why this was missed

fix reload saved variants calls

---

reference_data/management/commands/utils/download_utils.py
reference_data/management/commands/utils/download_utils_tests.py

Nodes for review:
1. The `tempfile` in the parameter `def download_file(url, to_dir=tempfile.gettempdir(), verbose=True):` can't be mocked because the default value of the parameter is generated before mocking being run. So I leave it un-mocked.
2. The exception in line #47 of `reference_data/management/commands/utils/download_utils.py` is un-reachable.
3. It seems that `responses` cannot mock the `urllib`. So the `urllib.urlopen()` is mocked separately.

Added unit tests for download_file method.

---

reference_data/management/tests/update_all_reference_data_tests.py

These tests mock out all the real update functioning commands. The tests cover a command argument test, skipping/no-skipping update command tests, and exception tests.

Added unit tests for reference_data command update_all_reference_data

---

seqr/management/commands/add_project_tag.py
seqr/management/tests/add_project_tag_2_3_tests.py
seqr/management/tests/add_project_tag_tests.py

Changes:
1. Add `from __future__ import unicode_literals` to convert all str literals to unicode
2. Change the exception result tests to accommodate the error message differences between the Django libraries of Python2 and 3.
- Python 2 exception: 'Error: argument --project is required'
- Python 3 exception: 'Error: the following arguments are required: --name, --order'
Use regular expression assertion to avoid incompatibility between Python 2 and 3.

Converted seqr management command add_project_tag to Python3.

---

seqr/urls.py
seqr/views/apis/locus_list_api.py
seqr/views/apis/locus_list_api_2_3_tests.py

One thing weird is that the Python 3 Django doesn't do longest url matching. It is solved by reordering the url entries. No change to the urls other locus_list_api yet.

Converted locus_list_api to Python 2 and 3 compatible.

---

seqr/views/utils/pedigree_info_utils.py
seqr/views/utils/pedigree_info_utils_tests.py

We support a specific type of upload that takes a sample manifest sent by collaborators and parses it to create the corresponding families in seqr but also emails the PM team a parsed version of the file they need for submitting to GP for sequencing. This adds testing for that

Pedigree parsing unit test coverage

---

.travis.yml
install_dependencies.sh
seqr/utils/communication_utils.py
seqr/utils/file_utils.py
seqr/utils/gene_utils.py
seqr/utils/middleware.py
seqr/utils/redis_utils.py
seqr/utils/redis_utils_2_3_tests.py
seqr/utils/xpos_utils.py
seqr/utils/xpos_utils_2_3_tests.py
seqr/views/apis/staff_api_tests.py

I don't add `from __future__ import unicode_literals` to the file `seqr/utils/middleware.py` in purpose. 
If `unicode_literals` is imported then the `'\n'` in `exception_json['traceback'] = traceback_message.split('\n')` at line 40 will become a `unicode` type. In this case, if `traceback_message` is a Python 2 `str` and has unicodes in it, it will be a casting error.

Converted seqr.utils to be compatible with Python 2 and 3.

---

seqr/views/apis/staff_api.py
seqr/views/apis/staff_api_tests.py
ui/pages/Staff/components/SavedVariants.jsx
ui/pages/Staff/reducers.js
ui/redux/selectors.js
ui/shared/components/panel/variants/VariantGene.jsx

There is a staff-only page where you can see variants tagged across all projects broken down by tag, with the option to filter by gene. This change allows filtering by gene without first needing to select a tag, as requested in https://github.com/macarthur-lab/seqr-private/issues/804
Tis also adds a link to these new pages for staff users next to the gene displayed on variants as requested in https://github.com/macarthur-lab/seqr-private/issues/856

Staff gene variants

---

seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/json_to_orm_utils.py

When seqr would receive a bulk update for individuals it would make a database query for each family and each individual that needed updating, which caused it to time out on a 1500 individual update (see https://github.com/macarthur-lab/seqr-private/issues/869). This changes the code to query all the necessary records at once and only make one-record calls to create records, which greatly speeds up this endpoint

Individual update timeout

---

seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_utils_2_3_tests.py

There is a bug with how SV search handles recessive search (https://github.com/macarthur-lab/seqr/issues/1368). This changes the criteria for unaffected individuals in recessive search to match the behavior we want

Fix SV recessive search

---

ui/shared/components/panel/variants/Predictions.jsx
ui/shared/utils/constants.js

Some of the sort functions for variants fail and cause page JS errors if the data is sparse, which can happen in normal app use (https://github.com/macarthur-lab/seqr-private/issues/874)

Fix saved variant sorts

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_2_3_tests.py

Add error handing for when a specific dataset type search (i.e. SV) is disabled in a family where search in general is enabled. Currently just displays really weird results (https://github.com/macarthur-lab/seqr-private/issues/875)

Better error message when dataset type search disabled

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_2_3_tests.py

There is a bug in seqr (https://github.com/macarthur-lab/seqr/issues/1367) that occurs if a family has multiple indices containing different individuals. For instance, if the variant index has all 3 individuals, but the SV index only has 2 of them, seqr search gives an unhandled key error. This PR fixes it

fix multi index search when indices have subset of individuals

---

seqr/fixtures/1kg_project.json
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_2_3_tests.py
seqr/views/apis/project_api.py
seqr/views/apis/staff_api.py

The `hashlib.md5()` needs a byte-like parameter such as Python 2 `str` or `bytes`. It can't accept Python 3 `str` which is the same as Python 2 `unicode`. Therefore, encode the Python 3 `str` to `bytes` for the hash function.
Test: open https://seqr-dev.broadinstitute.org/variant_search/results/7c0f4ed48108b4e89966299cbaff7794?page=1&sort=xpos
Without encoding, there will be error `TypeError: Unicode-objects must be encoded before hashing`. After encoding, the error disappears. 
Another issue: Some of the `variant_tag_type` entries don't have an `order` field. In Python 3, it causes an error of `TypeError: '<' not supported between instances of 'NoneType' and 'float'` when sorting a `variant_tag_type` list with the `order` field as a key. Change the key to `variant_tag_type['order'] or 0` …

Fixed some of Python 3 bugs.

---

deploy/docker/seqr/Dockerfile

The seqr Python 3 docker container doesn't have the `cron` package installed. By comparing to the sear Python 2 dockerfile, it is figured out that the `cron` package will be installed while installing the `postgresql` package without the option of `--no-install-recommends`. The option is removed to fix the issue.

Fixed the issue of missing 'cron'.

---

deploy/docker/redis/Dockerfile

Bumps the version of redis. To deploy this change, build, push and redeploy the redis pod with the updated version. Note that the deploy command needs to be run with the `-f` force argument to actually rebuild the image properly. This has been tested on dev

Update redis version

---

seqr/views/utils/pedigree_image_utils.py
seqr/views/utils/pedigree_image_utils_2_3_tests.py

After the python 3 upgrade saving pedigree images does not work (see https://github.com/macarthur-lab/seqr-private/issues/882 and https://github.com/macarthur-lab/seqr/issues/1391#issuecomment-663221914), due to a missed change in opening in 'r' vs 'rb' mode. Our unit test did not use binary for our test images so they couldn't catch this edge case, so I updated the test

fix pedigree image saving

---

deploy/docker/seqr/entrypoint.sh

cron by default uses the wrong version of python which causes all our cron jobs to fail. Explicitly setting the desired python executable fixes the issue. I already updated the cron job running in prod to fix our backups so the purpose of this commit is just for future deployments

Fix python in cron

---

reference_data/management/commands/utils/download_utils.py
reference_data/management/commands/utils/download_utils_tests.py
reference_data/management/tests/update_dbnsfp_gene_tests.py
reference_data/management/tests/update_gencode_tests.py
reference_data/management/tests/update_gene_constraint_tests.py
reference_data/management/tests/update_hpo_tests.py
reference_data/management/tests/update_mgi_tests.py
reference_data/management/tests/update_omim_tests.py
reference_data/management/tests/update_primate_ai_tests.py

We missed a python 3 update issue in the manage commands for reference_data, because `urllib.urlopen` is not available in python3 but we had it mocked everywhere so we didn't catch it. This PR makes it work in python 3 and also updates all our tests to use the responses library instead of a mocked download so we will catch this sort of error better in the future.

fix reference data update in python 3

---

seqr/fixtures/new_variant_tag_types.json
seqr/fixtures/variant_tag_types.json

Adds tag types as requested in https://github.com/macarthur-lab/seqr-private/issues/894
We add tag type fixture data in 2 places: `variant_tag_types` is the master list of all tag types which is loaded whenever new instances of seqr are set up, and should always include all out core tag types. `new_tag_types` is a transitional list that allows us to add the new types to the existing database by running `./manage.py loaddata new_tag_types`, and once that command has been run its okay to update it to a different set of tags for the next update as we do here

add sv tag types

---

.travis.yml
deploy/docker/seqr/entrypoint.sh
docker-compose.yml
test_local_deployment.sh

Adding a script which runs `docker-compose up -d seqr` to the end of travis-ci. 
This runs relatively quickly, so I'd vote for keeping it on-commit. 
Changing the postgres port to 5433 within docker-compose was necessary to avoid conflicts with the travis-ci environment
which already has something running on 5432.
Also, there's a change to seqr entrypoint.sh meant to avoid this error:
https://travis-ci.org/github/macarthur-lab/seqr/builds/717251157#L3038
The seqr docker image would need to be rebuilt before the change would take effect.

Travis test local deployment

---

seqr/utils/file_utils.py
seqr/views/apis/igv_api.py
seqr/views/apis/igv_api_tests.py
seqr/views/apis/staff_api_tests.py

For most use cases, reading from a remote file in google we want the content as a string. However, for IGV reads we want raw bytes, so this makes the default behavior as desired and whitelists the use case where we want raw bytes. 
Fixes https://github.com/macarthur-lab/seqr-private/issues/908

fix file iter content type in python 3

---

seqr/management/tests/reload_saved_variant_json_tests.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/variant_utils.py

An endpoint was failing because the arguments being passed in to search were sets instead of lists, which caused search to fail

Fix update saved variants

---

seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/utils/test_utils.py
ui/shared/components/panel/variants/Predictions.jsx

The PR allows seqr to use 2 new fields that were recently added to the elasticsearch pipeline: 
- `splice_ai_splice_consequence`  is now shown as a hover-over for the splice ai prediction if present
- `rg37_locus` includes the lifted under coordinates fro grch38 variants. We were getting this value by doing the lift using python on every variant when results were returned, which is still supported for indices without this new field.  There are some inconsistencies between how the pipeline does lifting and how the python library does so its best to use the pipeline when possible (see https://github.com/macarthur-lab/seqr-private/issues/852). Also, the python lifting can be slow, so this should give us a search performance boost.

Search index updates

---

seqr/management/commands/reset_cached_search_results.py
seqr/management/tests/reset_cached_search_results_tests.py
seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/views/utils/test_utils.py
seqr/views/utils/variant_utils.py

Fixes https://github.com/macarthur-lab/seqr-private/issues/912
`unmapped_type` is only used by elasticsearch if there is an index that is entirely missing a field thats is sorted on. When searching across variants and SVs this is used because SVs don't have any of the predictors. However, it turns out that not all regular variant indices use the same data type for field values, so while on the index used for testing this functionality when it was first implemented everything was a `float`, across all indices there are `float`, `half_float`, `double, and `keyword`. This updates the code to dynamically use the correct type for the given index and field

Fix predictor sort

---

requirements-dev.txt
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/staff_api_tests.py
seqr/views/utils/test_utils.py

Our tests for elasticsearch currently mock out the python elasticsearch client library. As part of upgrading ES we will be upgrading the client library as well. Since we mock it out everywhere it is used, if there are change to how the library behaves our test won;t'catch them. Therefore, I'm updating our unit tests to instead mock out the actual requests to elasticsearch, and I let the client library generate and parse those requests in the test just as it does in real life. 
Note that the `responses` library we use in most of our tests for mocking out http requests does not work for requests created in python by the `urllib3` library which is what is generated by elasticsearch, so I added the `urllib3-mock` library to test those requests

Es test update

---

ui/pages/Search/components/VariantSearchResults.jsx
ui/shared/components/DataLoader.jsx
ui/shared/components/panel/search/VariantSearchResults.jsx

This fixes a bug I noticed where it does not correctly fetch some important context for searches in a few edge cases

fix loading context for searches

---

ui/redux/selectors.js
ui/redux/selectors.test.js

Fix for #1444 - Variant Search throws UI error - "TypeError: Cannot read property 'filter' of undefined
Build passed: https://travis-ci.com/github/ssadedin/seqr/builds/183471189

Fix for #1444 - ui undefined filter

---

seqr/utils/file_utils.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/igv_api_tests.py

bams and crams are binary data files and need to be opened as such for local files. Fixes the latest issue in this ticket: https://github.com/macarthur-lab/seqr/issues/1383#issuecomment-698366041

Fix local bams

---

ui/shared/components/panel/genes/GeneDetail.jsx

Monarch has moved their beta site to their main site and deprecated the beta link, so we need to update our URL

Fix monarch link

---

INCIDENTS.md
README.md
deploy/LOCAL_INSTALL.md
deploy/MIGRATE.md
deploy/READVIZ_SETUP.md
deploy/docker/elasticsearch/Dockerfile
deploy/docker/kibana/Dockerfile
deploy/docker/pipeline-runner/Dockerfile
deploy/docker/postgres/Dockerfile
deploy/docker/redis/Dockerfile
deploy/docker/seqr/Dockerfile
seqr/models.py
seqr/utils/elasticsearch/es_search.py
servctl
ui/package.json
ui/pages/Public/LandingPage.jsx
ui/shared/components/page/Footer.jsx

Now that we have moved the org for the seqr repo, this updates all the hardcoded links that use the old url. This is not necessary (transferring a repo causes all the old links to redirect correctly) but its nicer to have them updated
Also, I updated the "maintainer" for all the docker images to be the TGG, and changed the syntax for the maintainer since the old "MAINTAINER" syntax is deprecated (https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)

update references from macarthurlab to broad

---

.gitmodules
deploy/docker/pipeline-runner/Dockerfile
deploy/servctl_utils/deploy_command_utils.py
deploy/servctl_utils/other_command_utils.py
deploy/servctl_utils/yaml_settings_utils.py

We had added a submodule for the elasticsearch pipeline to the seqr repo to support local installations, but once we switched to docker-compose it was no longer necessary. Now that I have moved that repo, I updated the pipeline runner to used the moved repo, and just removed the submodule entirely rather than updating it. There were a couple of utiity fucntions in that repo that we were using for deployments, and I just copied those over

Remove pipeline submodule

---

seqr/fixtures/reference_data.json
seqr/views/apis/staff_api.py
seqr/views/apis/staff_api_tests.py
ui/shared/components/panel/HpoPanel.jsx

Fixes https://github.com/broadinstitute/seqr-private/issues/927
HPO updated their category mapping, which broke our parsing for the discovery sheet. This updates the discovery sheet to work with the new HPO categories per the discussion on the ticket, and also cleans up the category to discovery column mapping to make the code easier to understand/ more explicit

fix discovery sheet handling of updated hpo categories

---

deploy/kubernetes/postgres/postgres.gcloud.yaml
deploy/kubernetes/redis/redis.gcloud.yaml
deploy/kubernetes/seqr/seqr.gcloud.yaml

We recently updated kubernetes for our deployments from version 1.15 to 1.16 but we didn't update some of our deployment files to meet the spec for the new version. This fixes it

update kuberentes yaml for 1.16

---

seqr/urls.py
seqr/utils/elasticsearch/utils.py
seqr/views/status.py
seqr/views/status_tests.py

Adds a status endpoint that we can set up for monitoring in stackdriver. This endpoint is publicly available, so it does not return any details about our tech stack/ what our dependent services are. Instead, it checks if dependent services are up and logs errors if they aren't and we will set up alerting on those errors

Status endpoint

---

seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/utils/redis_utils.py
seqr/utils/redis_utils_tests.py

Seqr caches search results, but when data reloads it is crucial that the cache is reset, or users see weird/ inaccurate results (see https://github.com/broadinstitute/seqr-private/issues/935)
One reason why resetting the cache fails is that there are so many keys to delete that the reset times out. While caching is crucial in the shorter terms (especially for recessive searches where there is a bunch of post processing that we cache) search itself always completes in a reasonable amount of time, so having the results cache expire after a couple weeks won't cause any serious performance changes to the user, and will ensure that users can never see seriously outdated results

expire cached search results

---

deploy/kubernetes/nginx/nginx.yaml
deploy/servctl_utils/deploy_command_utils.py

This is the less invasive option for SQR-68, where we enable the modsecurity plugin for our existing ingress-nginx.
My understanding is that this includes the ruleset from https://github.com/coreruleset/coreruleset, and therefore we might need to upgrade our ingress-nginx controller periodically (and perhaps initially) to stay up to date. By default, it operates in detection-only mode, so we'd need some log alerts to let us know what's happening. I can also look into how to configure it to actually act on threats once we're confident that it won't break anything.
One open question I have on this:
- It looks like the ingress-nginx project provides a helm chart to deploy itself. Did we use that to deploy this ingress originally, or did we simply use the …

Enables modsecurity and owasp rulesets on ingress-nginx

---

settings.py

The access_type is `online` by default. It needs to be `offline`. Otherwise, the access_token can't be refreshed after expired in one hour.

Update the access_type from online to offline

---

seqr/fixtures/1kg_project.json
seqr/views/apis/staff_api.py

For manual variants there is more sparse data that causes an error during reporting. This fixes it

fix reporting for manual variants

---

deploy/servctl_utils/deploy_command_utils.py

Saw this while working on something else, and I felt like the `apply` in this if branch wanted to be a `delete`.

Deletes the kubescan deployment when delete_before_deploy is true

---

seqr/utils/social_auth_pipeline.py
seqr/utils/social_auth_pipeline_tests.py
seqr/views/react_app.py
settings.py
ui/pages/Login/components/Login.jsx

This PR adds the ability for existing users to be able to log in through Google, even before seqr is connected to AnVIL.
If the environment variable `GOOGLE_AUTH_CONFIG_DIR` is defined then Google auth is enabled. An existing seqr user can log in through Google if the user's email matches the Google account's email. Only when the environment variable `TERRA_API_ROOT_URL` is defined, seqr will use AnVIL for Google-signing-in user authentication.

Added Google auth for local users.

---

deploy/kubernetes/nginx/nginx.yaml

Two actual changes, and one comment added here:
1) disables a rule which caught things like `within` and `sort` contained in seqr's URLs. The rule is meant to prevent windows command injection, so I don't think we need to worry too much about them.
2) Modify the default list of allowed Content-Types. We had many POST requests to a `/api/matchmaker/v1/match` uri, which had the content-type set to `application/vnd.ga4gh.matchmaker.v1.0+json`, and these looked like legitimate requests to me.
3) The changed comment is above the removal of rule 920350 so that we remember what that does. This OWASP rule blocks requests from localhost/private networks. Many of the requests coming through kubernetes (both actual app traffic and health checking) appear to be internal traffic, and need to be …

Adds a couple of WAF config updates to handle some potential false positives

---

deploy/kubernetes/nginx/nginx.yaml

The rule update to allow the matchmaker content-type wasn't working. This rule change updates us to modsecurity's latest syntax, and appears to be correctly allowing our matchmaker requests through.

switch to the latest recommended modsecurity regex format

---

deploy/servctl_utils/deploy_command_utils.py

This allows us to use different gcloud client ids for different environments. This doesn't change the command you need to run to deploy secrets

Use diifferent secrets for different envs

---

deploy/kubernetes/nginx/nginx.yaml

This changes the WAF from detect-only to enforcing. Requests that match one of the OWASP filters will receive a 403.

enable the WAF

---

seqr/views/apis/staff_api.py
settings.py

These changes:
- sets Django back to the pre-3.0 default of X-Frame-Options response headers to `SAMEORIGIN`
- sets the proxy_to_kibana method to explicitly speak http, since kibana is not configured to speak https.

X frame options

---

deploy/kubernetes/nginx/nginx.yaml

Requests for completing google authentication were getting caught by the WAF because they contained the string `.profile` in the request uri (`.profile` is a common file that gets looked for when scanning for inadvertently exposed secrets).
I believe this whitelist will turn off that rule when the request uri begins with `/complete/google`.

adds a whitelist rule for requests to /complete/google

---

seqr/urls.py
seqr/views/apis/case_review_api.py
seqr/views/apis/case_review_api_tests.py
ui/shared/utils/constants.js

The recent updates to the case review pages changed permissioning such that case review fields were supposed to be updated via field-specific URLs, but I did not actually update the family fields to use these URLs. This makes that change and fixes those endpoints to work with the correct post body format

fix update family case review fields

---

deploy/servctl_utils/deploy_command_utils.py

It turns out this really brings down seqr when we deploy secrets, as the docker image uses the secret when it initializes the db but does not keep it synced. We will manage credential rotation by doing a manual process once a year, until we can move to a google managed postgres instance. I will update the secrets backups with the appropriate new file

do not regenerate postgres password

---

deploy/kubernetes/nginx/nginx.yaml

`PUT` requests to `/api/telemetry/v2/userHasSeenNotice` were being denied by the WAF, which meant we couldn't dismiss a popup/notice that kept appearing inside kibana.

whitelists a request that was being issued to dismiss a popup in kibana

---

deploy/kubernetes/redis/redis.gcloud.yaml
deploy/kubernetes/seqr/seqr.gcloud.yaml

Linkerd's protocol inspection appears to create issues with seqr's communication to redis (I suspect this is our bug: https://github.com/linkerd/linkerd2/issues/5344). We didn't see this in dev, but our testing wasn't really sufficient.
skipping these ports fixed search within seqr prod -- we'll try the proposed fix from the upstream issue in dev once we can reproduce the problem there.

disable redis protocol inspection

---

deploy/kubernetes/postgres/postgres.gcloud.yaml
deploy/kubernetes/seqr/seqr.gcloud.yaml

This change is in response to pg_dumps failing in seqr. My understanding is that connections to the postgres database are succeeding and normal app usage is fine, but dumps are performing very slowly (or the connections are timing out and leaving the dump stuck part-way through). We'll have to test linkerd's new opaque ports setting when 2.10 is released. This may help with timeouts, but may not help with performance; we'll need further investigation later if that doesn't fix the problem.
Once the ports are exempted from the mesh, dumps succeed in a reasonable amount of time.

exempt postgres until we can try linkerd's opaque ports

---

deploy/servctl_utils/deploy_command_utils.py

We have a command for deploying pipeline runner as we need to maintain a docker image for local deploys. However, there is no pipeline runner kubernetes pod in our deployment so the `deploy_pod` line just fails and isn't needed

Fix deploy pipeline runner command

---

seqr/views/apis/dashboard_api.py
seqr/views/apis/dashboard_api_tests.py

Makes a deterministic order for project categories so we don't get occasional test failures due to order, like here: https://travis-ci.org/github/broadinstitute/seqr/jobs/753583608

fix flappy test for project export

---

deploy/kubernetes/seqr/seqr.gcloud.yaml

When skipping multiple ports, they need to be supplied in a comma separated string, or only the last annotation applies. So, in this case, redis was timing out after skipping the postgres port 😞 
I've applied this hotfix on prod, and both ports are now skipped there.

multiple port skips need to be a comma separated string

---

seqr/views/apis/auth_api.py
seqr/views/apis/auth_api_tests.py
seqr/views/react_app.py
seqr/views/react_app_tests.py
seqr/views/utils/terra_api_utils.py

All privileged users (data managers and superusers) must log in with Google Auth if Google Auth is enabled.

Added login restrictions to privileged users.

---

deploy/kubernetes/seqr/seqr.gcloud.yaml
deploy/kubernetes/shared-settings.yaml
matchmaker/views/matchmaker_api_tests.py
seqr/migrations/0020_remove_project_disable_staff_access.py
seqr/views/apis/dashboard_api_tests.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/apis/users_api_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/orm_to_json_utils_tests.py
seqr/views/utils/pedigree_info_utils_tests.py
seqr/views/utils/permissions_utils.py
settings.py

Changes the way PM and analyst permissions are handles in local installs. For local installations, where the user groups are not defined, PM permissions are made available to superusers and analyst permissions are not made available to anyone. This makes no changes tot our current production seqr, which will continue to use groups for PMs and analysts

Local pm and analyst permissions

---

requirements.txt
ui/package-lock.json

Bumps some of our dependencies that synk has flagged as having vulnerabilities. For the javascript packages, we do not need to update the version for any of our direct depndencies so there are no changes to package.json, but this updates the locked versions of several vulnerable downstream dependencies to their latest possible versions

Depenedency updates

---

deploy/docker/seqr/Dockerfile

This change allows forked repos to easily override the repository and branch when building their own images using [docker build-arg](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)
Overriding is optional and default values are the same as original.
E.g.:
```bash
docker-compose build \
--build-arg "SEQR_REPO=https://github.com/ssadedin/seqr" \
--build-arg "SEQR_GIT_BRANCH=mcri/master"
```
(cherry picked from commit 8c66148a8aa7f57e13de9e5320c2211cda80d6d3)

feat: Parameterised repo and branch when building Seqr image

---

seqr/utils/middleware.py
seqr/views/apis/dashboard_api_tests.py
seqr/views/apis/project_api_tests.py
seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py

In dev I noticed that when my token refresh failed the API returned an unhandled 500 error and the ui did not show any sort of useful error message. This updates the middleware to correctly handle these errors and return the appropriate response code and json errors to the client

better error handling for terra errors

---

ui/shared/components/panel/search/VariantSearchResults.jsx
ui/shared/utils/constants.js

Similar to "family" sort, "last tagged" sort should only be shown on the saved variant page, not the search page

do not show last tagged sort on search page

---

deploy/servctl_utils/deploy_command_utils.py
servctl

I am always stressed out that the `servctl deploy secrets` command deletes and redeploys all secrets for a given environment, since usually I am only updating secrets for one particular component and am worried that I might accidentally be messing up the other ones. This modifies the command parsing so while you still can redeploy all the secrets, you can also specify what component's secrets you want to update, i.e. `servctl deploy secrets nginx`

deploy secrets for individual components

---

.github/workflows/local-install-tests.yml
.github/workflows/unit-tests.yml

We want to avoid hitting our GCR repo on every PR commit, so this switches the local install tests workflow to only run on changes to the dev and master branches.

Move the heavier tests to a workflow that only runs on release branches

---

.github/workflows/unit-tests.yml
README.md

We had a build status badge in our readme referencing travis, this updates the readme to include badges for our github actions workflows.

Update build badges for Actions

---

settings.py

Currently, we use the default django session expiration which is 2 weeks, but for compliance it needs to be shortened to a day

expire sessions after 1 day

---

seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py

Currently this kind of search fails with an opaque Internal Server Error, so adding error handling to provide better user experience

limit download variants to under max variants

---

seqr/utils/communication_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/users_api.py
seqr/views/apis/users_api_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/pedigree_info_utils.py
seqr/views/utils/pedigree_info_utils_tests.py
seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py
seqr/views/utils/test_utils.py
ui/pages/Project/components/ProjectCollaborators.jsx
ui/pages/Project/components/ProjectCollaborators.test.js
ui/pages/Project/components/ProjectPageUI.jsx

Fixes email to send as actual HTML, and disables adding collaborators for AnVIl projects. While we need to keep user management for editing and removing users, one a project has been linked to AnVIL the only way to grant acccess must be through AnVIL itself

Anvil tweaks

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py

There are endpoints that need to check that  user has ever logged in with google (i.e has a valid google account) but recent changes added a check for access token. Since AnVIL isn't live yet, obviously no one has an access token set and this is making it impossible for users to access these pages. This change the is_google_authenticated helper back to its original purpose, and beefs up the is_anvil_authenticated helper and uses that in more places

Fix airtable access

---

seqr/management/commands/clear_project_tags.py
seqr/management/tests/clear_project_tags_tests.py
seqr/models.py

Add a command to clear tags from demo projects. This type of request happens with some regularity so we should have an actual command for this, instead of me bulk deleting things in the db

Clear demo tags

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

BASE_URL always has a trailing slash

fix link in anvil email

---

seqr/utils/logging_utils.py
settings.py

We get a lot of noisy error alerts for dev that we don't want, so this disables them. Also, stops logging a null traceback which makes logs harder to read

tweak logs for better debugging

---

reference_data/admin.py
seqr/admin.py

For compliance purposes, we need a record of all changes to the database made through the django admin. It turns out that the admin by default writes all changes (create, update, and delete) to a table in the database with all the necessary metadata we need. This PR makes that table viewable in the admin itself so we can easily see what changes were made if we are ever asked about it.  I also tweaked some of the existing admin display while I was in there

Admin logging

---

ui/pages/Project/components/CreateVariantButton.jsx
ui/pages/Project/components/Matchmaker.jsx
ui/pages/Project/components/SelectSavedVariantsTable.jsx
ui/pages/Project/selectors.js
ui/shared/components/panel/variants/Variants.jsx
ui/shared/components/panel/variants/selectors.js

Creates the ability to associate existing tagged variants with newly created manual variants. For SNVs this is used for multinucleotide variants, for SVs this will be used for complex SVs. Requires adding support for more than 2 "paired" variants (currently we only pair compound hets, which are always exactly 2). See linked ticket for details

Create Mnv/ complex SV

---

settings.py

django uses a `SECRET_KEY` setting that is used as part of the hashing to determining whether or not a session is valid. Users have been complaining recently of being frequently logged out of seqr and there are a ton of "Session data corrupted" warning logs. Django makes it clear that resetting the `SECRET_KEY` invalidates all active sessions, so you are supposed to keep this a constant. We have a `django_key` secret in our deployment that gets assigned to the `DJANGO_KEY` environment variable which will persist across seqr deployments. However, for some reason seqr defaults to getting the key from a file, and if that file is missing it generates a new key, only using the env variable if that fails. While we need to keep the file generation method for local users (who will need a key …

use kubernetes django secret key by default

---

ui/shared/components/buttons/EditProjectButton.jsx

editing large projects is getting a 413 from nginx because we are sending the whole project json which is very large. Instead, we should only send the fields that actually might have been edited

only send necessary update fields

---

seqr/views/apis/report_api_tests.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/apis/superuser_api_tests.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/test_utils.py

Instead of redirecting logged in users to the login page when they try to access something they don't have permission for, return a 403 error instead

Better permission denied error

---

seqr/urls.py
seqr/views/apis/dashboard_api.py
seqr/views/apis/dashboard_api_tests.py
ui/pages/Dashboard/components/CategoryIndicator.jsx
ui/pages/Dashboard/components/CategoryIndicator.test.js
ui/pages/Dashboard/components/ProjectsTable.jsx
ui/pages/Dashboard/selectors.js
ui/shared/components/table/DataTable.jsx

Currently we have a server-side endpoint to download the project dashboard data, but moving the download code to be based off of the client side table is a) more consistent with how almost every download in seqr works and b) easier to maintain and less fragile

Dashboard download client side

---

deploy/docker/seqr/readiness_probe

After updating seqr to no longer support a login page when google auth is enabled, the readiness probe fails

remove login from readiness check

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
ui/shared/components/panel/variants/Annotations.jsx
ui/shared/components/panel/variants/VariantIndividuals.jsx
ui/shared/utils/constants.js

Change the SV_TYPE (e.g. BND) displays to descriptive ones (e.g. Translation).  Show the SV_TYPE details if they exist in the hove-over messages.
Also, replace X/- notation with ref/alt.

Changed the genotype and SV type info displays.

---

settings.py

* Included both style-src-elem and style-src in CSP settings
* Kept style-src as fallback for Firefox as style-src-elem is not supported.

Included style-src-elem and style-src in CSP settings (Firefox fix)

---

seqr/utils/communication_utils.py
seqr/views/apis/users_api_tests.py

Fix associated to change [b32a8fd4f8a52be14f0c3d17289eb631f1381b0e](https://github.com/broadinstitute/seqr/commit/b32a8fd4f8a52be14f0c3d17289eb631f1381b0e)
(cherry picked from commit 8b8616a429bfc1a944ecae4060add61bad95a195)

fix: Fixed welcome email URL for first time users setting their password

---

seqr/utils/file_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
ui/pages/AnvilWorkspace/components/LoadWorkspaceDataForm.jsx

I finally come up with a solution without using any 3rd-party tools. Just load the VCF header line and retrieve the sample IDs in the line, and then compare the individual IDs to those sample IDs to find out if there are any missing IDs.
The delay is around 4 seconds which includes two almost equal parts: one is to get the VCF file name, another is to get the samples from the VCF file. If the user provides a VCF file name directly in the `Path to the Joint Called VCF` field, then the delay will be cut in half.

Ensure no missing samples in the VCF

---

ui/pages/Project/components/FamilyPage.jsx
ui/pages/Project/components/FamilyTable/IndividualRow.jsx
ui/pages/Project/components/FamilyTable/header/TableHeaderRow.jsx
ui/pages/Project/components/Matchmaker.jsx
ui/shared/components/buttons/FamilyLink.jsx
ui/shared/components/panel/family/Family.jsx
ui/shared/components/panel/family/Family.test.js
ui/shared/components/panel/family/FamilyFields.jsx
ui/shared/components/panel/family/FamilyLayout.jsx
ui/shared/components/panel/family/FamilyReads.jsx
ui/shared/components/panel/family/FamilyReads.test.js
ui/shared/components/panel/variants/Variants.jsx

As a precursor to an upcoming PR, this cleans up the family panel files. It moves them into a sub-folder and splits the huge `family.jsx` into a smaller `Family.jsx` with helper components contained in 2 other files - `FamilyLAyout.jsx` and `FamilyFields.jsx`
There are no behavior changes associated with this PR, and all the code was essentially copy-pasted

Family component file cleanup

---

deploy/kubernetes/shared-settings.yaml

This does not change anything in our live deployments, but when I need to spin up a loading cluster I uncomment and use this configuration, and RGP has gotten big enough that we now need 3 nodes instead of 2, so it would be helpful to keep that committed in code so I don't need to remember it

update num nodes for loading pool

---

seqr/models.py
seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/summary_data_api.py
seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/project_context_utils.py

Moves  functionality for getting all the project details and child entities from 2 separate sets of functions in the project api and variant search api into a shared utility that is used by both. No changes to functionality, but will make changes in an upcoming PR easier to implement/ read

Project context cleanup

---

seqr/fixtures/1kg_project.json
seqr/management/commands/lift_project_to_hg38.py
seqr/management/tests/lift_project_to_hg38_tests.py
seqr/views/apis/dataset_api.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/dataset_utils.py

We should only send a slack update for samples if data has never been loaded for that individual before, not just if the sample models itself is new. Also cleans up the `match_sample_ids_to_sample_records` a bit and moves shared behavior into the shared utility function

Fix new sample notification

---

deploy/docker/redis/Dockerfile

The version of the redis docker image we are using is no longer supported. This bumps us to the latest version.
In the long run, we should really consider not maintaining our own copy of external docker images, and also should consider switching to a GCP managed redis instance, but both of those are out of scope for this fix
This has already been deployed and tested in dev. Because redis is not a required service for seqr, there is no downtime while it is redeploying, so it is safe to go directly to production once approved
**Release Checklist**
OR 
- Already built and released on dev. Once approved will build for prod and push to registry and then redeploy to pod
- N/A

bump redis version

---

.cloudbuild/seqr-docker.cloudbuild.yaml
.github/workflows/docker-lint.yaml
.hadolint.yaml
CHANGELOG.md
deploy/docker/seqr/Dockerfile
deploy/kubernetes/seqr/seqr.gcloud.yaml

I think this is ready for an initial review. More changes to come eventually, but I think this is the smallest unit of work that improves our docker build to the point where we can start automating it. The resulting image here should be a little bit smaller in size than our current one, and should maintain equivalent functionality so that the `docker_build()` method could still be used for generating release images.
Major changes include:
- Rebasing our image on `python:3.7-slim-bullseye`. This is the official debian-based python image that provides python 3.7.12 presently. We also get upgraded from debian buster (which was EOL), but I don't think there's much we depend on there.
- Removing all the steps that download and compile python, since that is functionally provided by the python …

Docker Cleanup Part 1

---

seqr/utils/elasticsearch/es_search.py

There is an edge case when searching across many families in the same index where all the results for a subset of families have been loaded so `response_total` is a positive number but `response_hits` are empty

fix error on paginating large project searches

---

reference_data/management/commands/update_dbnsfp_gene.py
reference_data/management/commands/update_mgi.py
reference_data/management/tests/update_mgi_tests.py

Running `python -u manage.py update_all_reference_data --use-cached-omim` in our local instance resulted in errors.  One was a data issue in DBNSFP and the second was a change in format in the MGI report.  Raising this PR for reference.
I suspect this is not regularly run at Broad?  What's the process used at Broad to maintain these gene associated reference datasets?

Fix for reference data MGI parsing

---

CHANGELOG.md
deploy/kubernetes/gcloud-dev-settings.yaml
deploy/kubernetes/gcloud-prod-settings.yaml
deploy/kubernetes/seqr/seqr.gcloud.yaml
deploy/kubernetes/shared-settings.yaml
requirements.txt
seqr/urls.py
seqr/views/utils/orm_to_json_utils.py
settings.py

This PR adds a configuration option to use GCS to host the `MEDIA_ROOT` directory, with the goal of removing our dependence on a persistent GCP volume to store the data. This will enable us to redeploy seqr using more traditional kubernetes rollout semantics (which will be the way forward after #2344 )
If a `GCS_MEDIA_ROOT_BUCKET` isn't defined, the app will fall back to using a local directory for the `MEDIA_ROOT`, and will serve requests to `/media` with the builtin `django.views.static.serve` server. The intention here is for the behavior to remain unchanged for seqr local/docker-compose installs.

Use gcs media backend

---

deploy/kubernetes/shared-settings.yaml
deploy/servctl_utils/deploy_command_utils.py
docker-compose.yml

This bumps elasticsearch to the latest ECK operator and 7.x elasticsearch release. I PR'd this against master, since I think this will likely get deployed without anything else; let me know if that's not the case.
There was also still a `docker_build()` call in the `deploy_elasticsearch()` method, which I removed since I believe we're no longer using our custom elasticsearch image.
I think the deploy steps here are just to run the servctl deploy command for elasticsearch. But, I haven't done this particular upgrade before, so if you can confirm that, please do 👍 
Closes https://github.com/broadinstitute/seqr-private/issues/1087

Upgrade ECK to 1.9.1 and ES to 7.16.3

---

matchmaker/views/matchmaker_api_tests.py
seqr/utils/middleware.py
seqr/views/apis/auth_api_tests.py
seqr/views/apis/case_review_api_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/users_api_tests.py
seqr/views/apis/variant_search_api.py

Resolves security audit risk of disclosing too much information on a 403 response

do not return information on 403 response

---

deploy/docker/seqr/Dockerfile

It turns out cron has not been running since we updated out image in November
OR

add cron to seqr docker image

---

seqr/views/apis/project_api_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/test_utils.py

Does not change functionality, but improves test coverage for variant search, specifically adding test utility functions to make sure all the important fields can be tested on every call

Variant search test improvements

---

.cloudbuild/seqr-docker.cloudbuild.yaml

The cloudbuild file was only pushing the commit SHA tag and the `gcloud-{env}` tag (I had incorrectly assumed that cloudbuild would bump the `latest` tag on its own).
Let me know if there's other tags that we'd like to push. It looks like previously we were pushing a timestamp tag, but I'm unsure of what the utility of that was. Happy to add it if we'd like to keep it.

ensure that we also push the latest docker tag on auto builds

---

deploy/docker/seqr/entrypoint.sh
deploy/kubectl_helpers/redeploy_seqr.sh

Until we have a more automated release pipeline, servctl needs to know how to issue a restart to the seqr deployment for cases when we are only deploying a new image. Right now, seqr will correctly restart itself after a kubectl apply if anything about the kubernetes manifests change. However, if we're deploying an update that is only a new docker image that's using a moving tag (i.e. gcloud-dev, or gcloud-prod), then kubernetes won't notice that the deployment needs to be restarted.
To get the new image deployed, our options are:
- to run the servctl deploy with the `-d` option to force the pod to get deleted and then recreated, which will cause some short downtime
- After the docker image updates, manually running a `kubectl rollout restart deployment/seqr`, which shouldn't incur any …

Add kubectl rollout/restart support to servctl

---

ui/shared/components/form/FormWrapper.jsx
ui/shared/components/panel/search/VariantSearchFormContainer.jsx

small bug introduced in the FormWrapper change, for the search form we want the loading spinner to be explicitly tied to the variants loading and not the internal submitting promise. The only place we explicitly pass a loading prop to the form is for the search form, so this gets the desired behavior

properly clear search form loading on success

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
ui/pages/Project/components/ProjectOverview.jsx
ui/pages/Report/components/SeqrStats.jsx
ui/shared/utils/constants.js

Breaks up seqr stats based on internal projects vs external projects, and breaks apart sample counts by dataset type. No specific ticket, I just got frustrated by not being able to easily find these stats

seqr stat breakup

---

deploy/docker/seqr/Dockerfile

Two goals on this one:
1. I wanted to separate the `npm ci` (install) step from the `npm build` step. This should make it so that the docker build won't have to reinstall all node_modules every time something in `ui/` changes. It should only have to do that when either the docker cache has expired, or if the package/package-lock change.
2. Upgrades node to 14.x, and npm to v7 to match our developer laptop env. This appears to fix the issues i mentioned at standup with regards to the lockfile that is being generated with npm v7.
What's odd, is that the version of NPM we were getting from Debian was already v7, so it was able to handle the new lockfile, even with the older nodejs. The nodejs 14.x that comes from nodesource installs npm v6, which apparently couldn't handle the new lockfile, …

Various nodejs fixes for the docker image

---

deploy/docker/seqr/entrypoint.sh

This adds an until/retry loop that uses the `pg_isready` command from postgresql-client to determine if the postgres database is accepting connections before proceeding with the entrypoint (which includes the db migration scripts). If it's unable to connect to the database within 2 minutes, it exits the entrypoint. If that happens, the container goes into an Error state, and kubernetes will keep trying to restart the container on the same host until the entrypoint succeeds (and going into a BackoffLoop to retry at greater intervals after that).
Closes #2549

Wait for postgres connectivity

---

seqr/views/apis/project_api_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/test_utils.py
ui/pages/Dashboard/components/ProjectEllipsisMenu.jsx

On the server side, projects can only be deleted by the person who created them, which is the desired behavior. This updates the front end code to show the "delete project" button to the correct users

match ui to server permissions for project deletion

---

ui/pages/Search/components/filters/LocusListSelector.jsx

Passing in an undefined value to Dropdown does not select the blank option.
A string that matches one of the options must be passed up to BaseSemanticInput (and then semantic-ui-react). In this case a blank string works because there is a blank option in projectLocusListOptions.
This is for issue https://github.com/broadinstitute/seqr/issues/2601

Fix locus search dropdown, set dropdown to blank when an empty object is passed in as the locus list

---

ui/shared/components/table/LocusListTables.jsx
ui/shared/utils/constants.js

I added the Created Date as a column to both the CORE_FIELDS and BASIC_FIELDS, so that it would show on both the summary page and the modal (when adding a gene list to a project).
I think it would also be useful to show the filter in the modal, since on the Broad instance there are over 600 public gene lists. That can be a sepearte issue & pull request or I can add it to this request, whichever you prefer.
This is for issue https://github.com/broadinstitute/seqr/issues/2603

add Created Date to LocusListTables and set it as the default sort column

---

seqr/utils/elasticsearch/es_gene_agg_search.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py

This cleans up the utility functions/ classes for search. This will help with eventually swapping out the backend, and in the mean time cleans up the code to make behavior/ data flow cleaner. The biggest change is moving the logic for filtering variants to a single `filter_variants` helper in the search class itself, rather than keeping that logic in the utility function. As the logic complicated over time, that logic became more complex/ interconnected and it makes more sense to abstract it out

Search util cleanup

---

seqr/views/react_app.py
seqr/views/react_app_tests.py
settings.py

We can no longer uses the compiled `app.html` for local development since it doesn't exist so this instead updates seqr to use use the non-compiled `app.html` template for local development and updates tests accordingly

Fix static assets for local dvelopment

---

seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/permissions_utils.py

For the "all project" search we actually don't want to include variants from AnVIL-only projects for the data managers. We only have access to those projects for the purposes of loading and debugging so we shouldn't be getting variants back from those projects in any standard search. If a data manager really needs to debug a search issue on an AnVIL project, they can still do searches directly in that project

all project search context for data managers

---

ui/pages/Search/components/filters/LocusListSelector.jsx
ui/shared/components/panel/search/LocusListItemsFilter.jsx
ui/shared/components/panel/search/VariantSearchFormContainer.jsx
ui/shared/components/panel/search/VariantSearchFormPanels.jsx
ui/shared/components/panel/search/constants.js
ui/shared/utils/constants.js

This is a precursor Pr for https://github.com/broadinstitute/seqr/issues/2656 . It cleans up the way the panel app gene lists are handled in the location panel in preparation for other changes to that panel. It has no changes to display/ behavior/ performance, it just makes the code easier to work with going forward
Change summary:
Currently, panel app gene lists are added to the same form field as regular lists, but they are formatted a a dictionary instead of a string, and the `LocusListItemsFilter` has conditional logic to render it based on type, and then before the form is submitted it post processes the object into a string. This changes the form to use a separate field for panel app list data, uses a decorator to keep the string and object values in sync to remove the need for post …

Panel app gene search cleanup

---

deploy/docker/pipeline-runner/Dockerfile

bug leftover from switching all `cd` calls to `WORKDIR`. The updated image has already been built and pushed
OR 
-  pipeline-runner image is build/ pushed

fix pipeline runner perl installation

---

seqr/fixtures/1kg_project.json
seqr/management/tests/load_rna_seq_tpm_tests.py
seqr/urls.py
seqr/views/apis/family_api.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/summary_data_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/variant_utils.py
ui/redux/selectors.js
ui/redux/selectors.test.js
ui/shared/components/panel/variants/RnaSeqTpm.jsx
ui/shared/components/panel/variants/RnaSeqTpm.test.js
ui/shared/components/panel/variants/VariantGene.jsx
ui/shared/components/panel/variants/selectors.js
ui/shared/components/panel/variants/selectors.test.js

Fetching the RNA TPM data for all the saved variants for large projects takes about a full minute. Rather than fetching the data with the variants, we should instead just indicate if a family has data or not, and then fetch it dynamically when the user actually wants to view the data

Variant rna seq performance

---

deploy/servctl_utils/deploy_command_utils.py
deploy/servctl_utils/other_command_utils.py
deploy/servctl_utils/shell_utils.py

When we moved the configuration for disks from servctl to terraform, it ended up breaking the code for creating persistant volumes for the disks in kubernetes, which in turn breaks our elasticsearch deployment. This updates the pv code to instead create one pv for every data pod. It also fixes a bug in the command error handling that caused commands which raise multiple errors to be ignored if one of the errors is ignorable, instead of checking each error, which caused the deployment to proceed without a pv when that failed

Fix es pv creation

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

Error logs send push notification and are intended for unexpected/ unhandles errors that occur in the app. Since DAGs being unable to trigger while already runiing is expected behavior that notifies us via slack, it should not be pushing error notifications as well, so we should log a warning instead

send warning on dag trigger failure

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/utils/test_utils.py

Implements the final outstanding feature from https://github.com/broadinstitute/seqr/issues/229 to prevent the confusion as caused in https://github.com/broadinstitute/seqr/issues/2710
Sets a selected main transcript for variants where the worst transcript was not actually one of the filtered transcripts from search. The UI for this already exists for saved variants, so no UI code change is needed to properly display the selection

select main transcript that has filtered annotation

---

seqr/fixtures/1kg_project.json
seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/orm_to_json_utils.py

Fixes https://github.com/broadinstitute/seqr/issues/2749 and sets desired behavior that the fields explicitly set on the model always override anything cached in the json

saved variant model fields supercede cached json

---

ui/pages/Public/components/LandingPage.jsx

The actual link was updated from the preprint to the main paper in a previous PR, but we accidentally left the word preprint here

update preprint link label

---

deploy/docker/pipeline-runner/bin/download_reference_data.sh
deploy/docker/pipeline-runner/vep_configs/vep-GRCh38-loftee.json

Fixes the issue discussed in https://github.com/broadinstitute/seqr/discussions/2695#discussioncomment-2816230
The docker image with these changes has already been built and pushed to the registry. 
OR 
- N/A

add fasta file for local pipeline

---

deploy/kubernetes/shared-settings.yaml
deploy/servctl_utils/deploy_command_utils.py

Since we're now deploying the ECK operator and linkerd using argocd, this removes the steps that installed them from the servctl script.
Closes https://github.com/broadinstitute/seqr-private/issues/1151
Does the first half of https://github.com/broadinstitute/seqr-private/issues/1108 -- the rest of that can be done once our seqr helm chart is responsible for the Elasticsearch manifests that deploy the ES cluster itself.

Remove linkerd and eck operator installs

---

.github/workflows/dev-release.yaml

This adds a docker build workflow that is triggered off of successful completions of the Unit Tests workflow on the seqr-helm-version branch. This will allow me to test our dev release workflow when I push changes to that PR/branch. Our normal dev/master docker builds are still in place, and this should have no effect on them.
This has to go into the master branch, because apparently workflow_run triggers only work if the workflow you're defining exists on the repo's default branch (see the Note [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)).

add a dev release workflow for testing

---

.github/workflows/dev-release.yaml

This is a fixup for #2896 -- `$GITHUB_SHA` points to the latest commit of the default branch on workflows triggered by the workflow_run event. Instead, we need to use the `github.event.workflow_run.head_sha` in order to make sure we tag the docker image using the commit from the branch that actually triggered the workflow
OR

use the triggering workflow shasum

---

.github/workflows/dev-release.yaml

This updates the dev release workflow to track the dev branch, and adds a step that updates the docker image tag in the broad-seqr helm chart for eventual release. Once this merges, we'll want to remove the google cloudbuild trigger that we have for dev, as this will now be the thing responsible for kicking off the docker build there. The prod cloudbuild trigger will stay intact, and there'll be a PR similar to this one to add the prod release workflow once we're ready to release that.
Again, this has to merge into master, since github requires `workflow_run` style jobs like this one to be defined in master/the repo's default branch.
OR

Adds helm chart update workflow for dev releases

---

.github/workflows/dev-release.yaml

This should fix https://github.com/broadinstitute/seqr/actions/runs/2906358172/workflow
OR

fix the misplaced needs setting in the dev release flow

---

.github/workflows/dev-release.yaml

One day, github will allow you to test and/or validate workflows like this without them being on the default branch. But today is not that day. 🤦 
The version tag of the yq action was incorrect, and the git pull of our tgg-helm repo needed to be authenticated. I pushed a test version of this workflow that I could trigger manually and validated that it was working there: https://github.com/broadinstitute/seqr/runs/7979089669?check_suite_focus=true
OR

Fix yq tag, authenticated git pull

---

.github/workflows/unit-tests.yml

This adds some caching steps to the pip and npm installs to hopefully shave some time off the unit tests pipeline.
I also noticed that we were running a much older version of nodejs in our actions tests than we do in the seqr docker image, so I updated that to version 14 to match.
Last change was updating the `npm install || true` to a [`npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci), which we also do in docker. I think this is the preferred way to run NPM in automated environments, according to the docs, since it only installs explicitly what's in the lockfile, rather than upgrading everything in the dependency tree like `install` does. It's also much faster.
Fixes #2895

Add actions caching, update actions node to match docker

---

ui/pages/Project/components/PageHeader.jsx

This button is missing a prop which is causing the matchmaker page render to fail, but actually that button shouldn't be ob on the matchmaker page anyways so I removed it

remove extra edit project button

---

seqr/utils/file_utils.py
seqr/utils/file_utils_tests.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

If you run `gsutil ls gs://bucket/**` on an empty bucket it throws an error instead of just returning an empty list, which causes unfriendly error to be raised if a user tries to load data from a fully empty workspace. This happened in production and was a bit hard to debug so I added some additional logging here that would have helped me

Handle get VCF error on empty bucket

---

ui/pages/Project/components/EditDatasetButton.test.js
ui/pages/Project/components/EditDatasetsButton.jsx
ui/pages/Project/fixtures.js

This makes 2 necessary changes to the conditional logic for the new load anvil to project button:
1) Addds a check that the project already is associated with a workspace before allowing the user to request additional data
2) Shows the main edit datsets button to data mangers/ PMs so they can continue to do their jobs, instead of showing them the request additional data button

Edit datasets button - no anvil

---

seqr/utils/communication_utils.py
seqr/views/apis/users_api_tests.py

I just realized we forgot to clean this up when we switched access. This helper function can no longer be called if anvil is enabled so theres no need to support and anvil email

clean up unreachable anvil welcome email code

---

.github/workflows/prod-release.yaml

This adds a workflow intended to facilitate production releases after merges to master. Once the unit tests workflow succeeds on that branch, a docker build will trigger that pushes tags for the master commit ID and the gcloud-prod tags. Following that, a pull request will be opened on the seqr helm chart updating its appVersion.
We're not deploying prod with the helm chart yet, so this won't change anything with how we currently _ship_ prod with servctl. But, it will be responsible for doing the docker build for the master branch. Prior to merging, I'll need to disable the [old out-of-band cloudbuild trigger](https://github.com/broadinstitute/seqr-terraform/blob/main/prod/cloudbuild.tf) which won't be necessary anymore with Github Actions running the build.
OR

Add Prod chart update workflow

---

seqr/views/apis/family_api_tests.py
seqr/views/apis/individual_api.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/superuser_api.py
seqr/views/apis/superuser_api_tests.py
seqr/views/apis/users_api.py
seqr/views/apis/users_api_tests.py
seqr/views/react_app.py
seqr/views/react_app_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/orm_to_json_utils_tests.py
seqr/views/utils/pedigree_info_utils.py
seqr/views/utils/pedigree_info_utils_tests.py
seqr/views/utils/permissions_utils.py

This is a pprecursor clean up before I start working on https://github.com/broadinstitute/seqr-private/issues/1176
We were returning a lot of user fields to the client that we did not need, and the functions to get the json for users/ lists of users were needlessly complex. This does not actually change seqr behavior

Clean up analyst user json

---

seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py
settings.py

For https://github.com/broadinstitute/seqr-private/issues/1176 we will need the ability to query a list of group members as the seqr service account. This is because users need to be able to see the list of seqr analysts even if they are not themselves an analyst/ an admin on the analyst group. In order to use google OAuth's recommended service account credentials library, I reworked how we do the initial service account oauth in the setting file so I wanted to have this reviewed separately from the coming-soon much larger analyst reworking PR

support service account authorization for anvil access

---

.github/workflows/prod-release.yaml

As discussed in standup, releasing the prod environment after this automation makes its changes to the helm will still require  a manual approval from us. Given that, opening a PR in seqr-helm feels like an unnecessary gate. This changes the workflow so that it just pushes a chart update commit instead.
OR

remove PR step from helm chart update and use a commit

---

ui/shared/components/form/AnvilFileSelector.jsx
ui/shared/components/form/LoadOptionsSelect.jsx

makes the VCF loader select generic so it can be used for any dropdown that should load its own options without adding them to the redux state. This will be user more broadly in my upcoming PR, but this is a stand alone change so it wil be easier to review it separately

use generic load options select class

---

seqr/views/apis/dashboard_api_tests.py
seqr/views/utils/permissions_utils.py

Currently, if `get_project_guids_user_can_view` is called for a data manager with `limit_data_manager=True` the limited projects are cached. Then if it is called again before the cache expires with `limit_data_manager=False` it returns the cached value which is the limited list and not the full list, which is an incorrect list of values. For the no limit case, theres no need to cache at all as there is no external requests or processing being done

do not cache unlimited data manager project guids

---

matchmaker/views/external_api_tests.py
matchmaker/views/matchmaker_api_tests.py
seqr/fixtures/1kg_project.json
seqr/fixtures/reference_data.json
seqr/management/tests/reload_saved_variant_json_tests.py
seqr/views/apis/awesomebar_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/apis/variant_search_api_tests.py

For an upcoming update to matchmaker submissions, submissions will need to be associated with saved variants. This updates the text fixtures and any affected tests to make it possible to test that new functionality.

Text fixture update

---

seqr/views/apis/users_api_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/test_utils.py

`permission_levels` are always lower cased but the analyst group name in AnVIL is not all lower case so we are not correctly fetching anvil users for that group

handle case sensitivity for anvil groups

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/individual_utils.py
seqr/views/utils/json_to_orm_utils.py
seqr/views/utils/pedigree_info_utils.py
seqr/views/utils/pedigree_info_utils_tests.py
ui/shared/components/panel/LoadWorkspaceDataForm.jsx

Our pedigree utility function did not correctly detect new individuals with no sex or affected status when geenrating the list of updated individuals. This fixes that bug, and also requires AnVIL users to include sex and affected status in the pedigree file  since they really should be providing that (although they can leave it blank of they really don't know)

Anvil sample subset bug

---

deploy/kubectl_helpers/restore_local_db.sh
deploy/kubectl_helpers/shell.sh
deploy/kubectl_helpers/utils/get_pod_info.sh
deploy/kubectl_helpers/utils/get_pod_name.sh

The latest helm release changes the labels for the pods, so this updates the helper scripts to correctly access them, and also fixes a long standing issue with setting the container name when shelling into a pod

Fix kubectl helpers

---

docker-compose.yml

Now that we no longer are maintaining our own redis docker image, we shouldn't reference it in the local docker compose

update docker-compose redis

---

matchmaker/views/matchmaker_api.py
matchmaker/views/matchmaker_api_tests.py
seqr/urls.py
ui/pages/Project/components/Matchmaker.jsx
ui/pages/Project/fixtures.js
ui/pages/Project/reducers.js
ui/pages/Project/selectors.js

Parallelizes matchmaker search behavior so each nodes is searched in their own API request instead of all being searched sequenctially. This should fix the timeout issues we have been getting since taking RD Connect live

Mme performance

---

deploy/docker/seqr/entrypoint.sh

Seqr itself (in settings.py) pulls the postgres username from the environment variable that we set in the deployment. But, our entrypoint script was passing "postgres" as the username to the psql actions.
I think it's probably best to let this roll through dev first, and then it can just go out in the next prod deploy if it looks good there.

Fix hardcoded postgres username in entrypoint

---

seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
ui/pages/Project/components/AnalysisGroups.jsx
ui/pages/Project/components/EditDatasetsButton.jsx
ui/pages/Project/components/FamilyPage.jsx
ui/pages/Project/components/FamilyTable/FamilyTable.jsx
ui/pages/Project/components/GeneLists.jsx
ui/pages/Project/components/ProjectCollaborators.jsx
ui/pages/Project/components/ProjectOverview.jsx
ui/pages/Project/components/ProjectPageUI.jsx
ui/pages/Project/components/SavedVariants.jsx
ui/pages/Project/components/VariantTagTypeBar.jsx
ui/pages/Project/components/VariantTags.jsx
ui/pages/Project/components/edit-families-and-individuals/BulkEditForm.jsx
ui/pages/Project/selectors.js
ui/redux/rootReducer.js
ui/redux/utils/reducerUtils.js
ui/shared/components/graph/HorizontalStackedBar.jsx

Data for the project page is loaded in several separate requests. This was badly impacting the preformanceof the project page, as when each request completed any component that had the current project as a prop re-rendered. There were 3 categories of changes I made to address this:
1) Change the response from the server to remove the `<families/overview/etc>Loaded` field from the project response, and instead keep track of which entities have been loaded directly in the state, removing unnecessary updates to the project object
2) Instead of connecting several props to a top level component to pass down to its children, connecting the children directly and removing props from the parent, so when a part of the data updates only the relevant child component updates (i.e. instead of …

Overview  UI performance

---

seqr/views/apis/report_api_tests.py
seqr/views/utils/airtable_utils.py

Split airtable requests with many OR filters into multiple requests in order to prevent the query URL from being too long

Sample metadata 414

---

seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/orm_to_json_utils.py
ui/pages/Project/components/SavedVariants.jsx

Fixes the reported bug and a new bug from my lasrt PR that returns duplicate family guids for saved variants

Family saved variant fix

---

panelapp/pa_locus_list_api_tests.py
seqr/views/apis/locus_list_api.py
seqr/views/apis/locus_list_api_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/variant_utils.py
ui/redux/selectors.js
ui/shared/components/table/LocusListTables.jsx

Changes the locus list json function to use the faster queryset logic. As part of this, there was conditional logic in the endpoint for fetching the full list of items associated with every list, which was really overkill as the only place that was used was for being able to filter a table of locus lists by gene name. To improve performance, I therefore changed that endpoint to only return the gene names, and moved the logic for fetching all the items into the single `get_json_for_locus_list` function

Locus list queryset

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/airtable_utils.py

This improves performance for single-project sample metadata pages by reducing the total number of airtable calls. Most airtable records have a `CollaboratorSampleID` that maps to the seqr ID, but a relatively small subset have a different value for this, and the actual seqr ID is stored in `SeqrCollaboratorSampleID`. Since there is a URL query limit, we are limited in the number of or filters we can send per request, so in the previous approach of filtering for either one of those fields we essentially double the number of airtable requests we make (i.e if there are 400 samples at 200 filters per request we need to make 4 requests instead of only making 2 requests if we could only filter on one field). This change first runs the query for all the records that match the …

Sample metadata performance

---

seqr/fixtures/1kg_project.json
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/export_utils.py

FIxes a few outstinding issues with the gregor report:
- Filters projects to the Gregor category
- Fixes the prior_testing field
- Filters out rows where all values are blank, which occurs now due to sparse real-world metadata

Gregor report category

---

ui/pages/Project/components/FamilyTable/IndividualRow.jsx
ui/pages/Project/components/PhenotypePrioritizedGenes.jsx

The gene search link generated for phenotpye prioritization was not working because it was using the wrong field to pull the gene Ids. This fixes that, and also tweaks the display a bit to use a larger modal

fix phenotype gene search and tweak display

---

ui/pages/Project/components/CaseReview.jsx
ui/pages/Project/components/FamilyPage.jsx
ui/pages/Project/components/FamilyTable/CollapsableLayout.jsx
ui/pages/Project/components/FamilyTable/FamilyTable.jsx
ui/pages/Project/components/FamilyTable/IndividualRow.jsx
ui/pages/Project/components/FamilyTable/header/TableHeaderRow.jsx
ui/pages/Project/components/ProjectPageUI.jsx
ui/shared/components/panel/family/Family.jsx
ui/shared/components/panel/family/FamilyLayout.jsx

Moves the behavior for toggling whether a FamilyLayout` component is collapsed or not into a helper component instead of implementing directly for Family table rows, so behavior can be easily shared for individual rows. This does require some tweaking for the display, but overall everything (except case review) looks the same

Individual row collapsed in case review

---

seqr/views/apis/report_api_tests.py
seqr/views/utils/airtable_utils.py

This improved the performance of fetching records from airtable by reducing the overall number and duration of requests. Airtable has a maximum page size of 100, and if your filter returns more than that many records it return a response with an offset param so you can page through the results. This means that when we were passing 270 filters per request, this was actually executing up to 3 requests to page through all the data. Switching to setting the number of filters to just below the max results per page means we almost never need to make an offset request. Consider the case where we are filtering to 375 records.
Before:
1.  Query for records 0-270
2. Query for second page  of records 0-270
3. Query for third page of records 0-270
4. Query for records 270-375
5. Query for second page …

filter to single page of airtable records

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
ui/pages/Report/components/SampleMetadata.jsx

Allows users to opt to skip the airtable metadata in a single-project sample metadata table

allow skip airtable for sample metadata

---

ui/pages/Project/components/PhenotypePrioritizedGenes.jsx
ui/pages/Project/fixtures.js
ui/pages/Project/selectors.js
ui/pages/Project/selectors.test.js
ui/shared/components/panel/variants/selectors.js
ui/shared/components/panel/variants/selectors.test.js

Not  crucial, but one of the phenotype priority selectors is only used on a project page but is defined in the variant selectors, which makes it hard to track down and hard to understand where it is used and how it is safe to change it.  This moves it to the project specific selector file to make that more clear

move selector to correct file

---

seqr/models.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/users_api_tests.py
seqr/views/utils/dataset_utils.py
seqr/views/utils/file_utils.py
seqr/views/utils/test_utils.py

Based on the suggestion in the ticket I explored a few options for how to best test logging and ultimately decided to add a helper to our test function that redirects our log stream to a string buffer that we can access at any point in the. tests. This means we are able to test whatever the actual log output is. 
I then fixed the logging bug reported in the ticket, as well as a few other small bugs I caught once we actually had good testing for logs. I think eventually we will want to make these updates for everywhere in our tests that are mocking loggers, but that seems out of scope for this PR

Bulk create logging error and better logging tests

---

seqr/utils/file_utils.py
seqr/utils/file_utils_tests.py
seqr/views/apis/anvil_workspace_api_tests.py

For many files, we are running into a documented issue when using `wait` with stdout piping. Switching to the recommended `communicate` function fixes the issue: https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

Fix read many files from GS

---

seqr/views/apis/igv_api.py
seqr/views/apis/igv_api_tests.py
ui/pages/Project/reducers.js

`individualsByGuid` is no longer initially loaded with the project page state so formatting error messages on IGV loading is failing. This change more explicitly maps the user-provided ID to the error message shown to the user

Fix error formatting for IGV loading 

---

seqr/management/tests/lift_project_to_hg38_tests.py
seqr/utils/search/add_data_utils.py
seqr/utils/search/constants.py
seqr/utils/search/elasticsearch/es_utils.py
seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py
seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/dataset_api_tests.py

This implements all the remaining requests to the hail backend, or explicitly sets exceptions for requests we do not plan to support

Hail backend - add additional calls

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py

There are going to be substantial changes to which fields we query from airtable, so I would like the order of these fields to be  clear in the test so its easy to see what changed

better test stablity for gregor report

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/pedigree_info_utils.py

while implementing https://github.com/broadinstitute/seqr/pull/3444 there was an edge case in the code that was nearly impossible to test, essentially because `parse_pedigree_table` was being called in 2 different places with 2 pretty different sets of arguments, but the code had error handling for all the possible argument combinations. This splits the functionality out, creating a `parse_basic_pedigree_table` helper that only works on standard pedigree formats and does not allow all the extra arguments for the sample manifest

split parse pedigree functionality

---

seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py

Triggering the dag through the new UI fails if the directory has any non-version files or folders

handle invalid version directories for dag trigger

---

ui/shared/components/panel/variants/Annotations.jsx
ui/shared/components/panel/variants/Predictions.jsx
ui/shared/utils/constants.js

Add a link to the SpliceAI lookup page on the SpliceAI predictions

---

ui/pages/Project/components/FamilyTable/IndividualRow.jsx

Break the ExchangeMatching and the RNAseq links into different lines, and keep the spacing consistent.
Before:
After:

Break the RNASeq links into new lines

---

seqr/fixtures/1kg_project.json
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py

Discovered a bug in the sample metadata report if individual IDs are not unique across projects

handle dup individual ids for sample metadata

---

ui/shared/components/panel/variants/VariantIndividuals.jsx

fixes a bug with ref forwarding for the styled components package by removing an unnecessary usage of said library

fix variant warning icon hover

---

seqr/utils/search/elasticsearch/constants.py
seqr/utils/search/elasticsearch/es_utils_tests.py

I did not properly handle the fact that in elasticsearch missing keyword fields are nulls and not empty strings

properly format null vest values

---

seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_tests.py

Hi, we had some trouble updating metadata for non-feature columns - and I think a small refactor to this conditional would allow updating non-feature columns. My test was simply trying to update a single individual with a changed notes column.
Keen to understand more about this conditional to see if I'm misunderstanding the requirements for updating :)

Refactor check for updating non-feature columns

---

ui/pages/DataManagement/components/AddIGV.jsx
ui/pages/Project/components/EditDatasetsButton.jsx
ui/shared/components/form/IGVUploadField.jsx

Updates description for the "optional" gCNV column, and also combines the logic for the IGV upload field so future updates to this field can happen in one place instead of tracking it doen in multiple places

shared igv upload field

---

ui/.eslintignore
ui/.eslintrc
ui/package-lock.json
ui/package.json

This PR enables ESLint to support Typescript. Ref: https://typescript-eslint.io/getting-started
1. Configure ESLint to ignore `node_modules` and `config` directory.
2. Configure ESLint to support typescript.
Add a `Todo` comment in `.eslintrc`. After changing ESLint parser to typescript there were many errors related to types. Therefore I disabled a few of typescript rules. We will remove them from ESLint rules after completing the migration.
#2931

feat: enables ESLint to support TypeScript.

---

ui/.eslintrc

https://github.com/broadinstitute/seqr/pull/3682 redid and disabled a lot of the linting rules. We should update linting for typescript once that whole migration is done, and in the meantime keep our linting as is

Fix eslint

---

hail_search/queries/base.py
hail_search/queries/mito.py
hail_search/queries/sv.py
seqr/utils/search/search_utils_tests.py

Changes how variant-id specific queries are executed, uses query_table instead of filtering to specific variant IDs to improve performance

use query table for variant id query

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py

Updates the Gregor metadata reports to use the columns as defined in the data model instead of us also maintaining our own lists of columns. This means that when adding or modifying tables we do not have to keep our list of columns in sync with the Gregor data model and its much easier to make such updates, and if they add new optional columns we need to make no changes on our end

Gregor report - column refactor

---

seqr/fixtures/1kg_project.json
seqr/views/apis/report_api_tests.py
seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/utils/anvil_metadata_utils.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/test_utils.py

Allow sample metadata report generation to succeed if variants with no genes have discovery tags. Fail Anvil report, as this should not happen for any of our internally supported/reported projects

Sample metadata all error

---

hail_search/constants.py
hail_search/queries/base.py
hail_search/queries/multi_data_types.py
hail_search/test_search.py

Updates key_by behavior to keep datasets sorted by locus-allele instead of switching to the non-sorted variant_id

Remove hail shuffle

---

seqr/views/apis/report_api.py

In the real world, seqr projects either have exome or genome data but not both, and our report took advantage of that fact to choose the sample type from a random family. However, we have test fixture data with both which caused the test to flap occasionally. This updates the logic to explicitly set the samply type on a per family basis

explicitly set family sequencing approach in discovery sheet - fix flappy test

---

seqr/views/utils/file_utils.py
seqr/views/utils/file_utils_tests.py

There are plenty of places in seqr where a user uploads a file and then submits a form. seqr currently deleted these files after they are read, but this means if any of the downstream code for parsing that form and file return an error to the user and the user then resubmits the form, the file no longer exists. This is not intuitive to users, as the form still shows that a file has been loaded and also nothing else in the form was cleared after form submission failed so there no reason why that would be true for the file. Since these temporary files are always saved in a temp directory, there is really no need to clean them up explicitly and so leaving them and allowing them to be accessed on future form submissions will make for a better user experience. Also, accessing these files …

do not delete uploaded files after reading

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

This, I believe, is safe to go in at any time as I've rsync-ed everything over:
```
gsutil ls gs://seqr-hail-search-data/v03/GRCh38/
gs://seqr-hail-search-data/v03/GRCh38/GCNV/
gs://seqr-hail-search-data/v03/GRCh38/MITO/
gs://seqr-hail-search-data/v03/GRCh38/ONT_SNV_INDEL/
gs://seqr-hail-search-data/v03/GRCh38/SNV_INDEL/
gs://seqr-hail-search-data/v03/GRCh38/SV/
```

Rename `seqr-datasets` to `seqr-hail-search-data`

---

seqr/utils/file_utils.py
seqr/views/apis/igv_api_tests.py

Alright, I think I got it. It is because this [length here](https://github.com/broadinstitute/seqr/blob/6bd1328dad35c2182afb64b9756bd0a46cd13461/seqr/utils/file_utils.py#L57C28-L57C28) does not match [this length here](https://github.com/broadinstitute/seqr/blob/6bd1328dad35c2182afb64b9756bd0a46cd13461/seqr/views/apis/igv_api.py#L243).
Off by one error.
Discussion here: https://github.com/broadinstitute/seqr/discussions/3755
I also kept the status="none" in dd command.

Correct length of cram block is returned by dd.

---

seqr/utils/vcf_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

If a user requests data loading through AnVIL, this adds an additional validation that if the provided VCF specifies the genome build in its VCF meta we confirm that the user-provided genome build matches. Not all VCFs have this metadata, and we do not throw an error if it is mssing

validate vcf meta reference version

---

seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/variant_utils.py

The conditional logic for returning RNA expression data in search results was broken and wa snot always returning the data when needed

properly return tpm genes for all searches

---

ui/shared/components/form/XHRUploaderField.jsx
ui/shared/components/form/XHRUploaderWithEvents.jsx

A user got a confusing error message caused by an edge case where he submitted a form while a required file was in the process of re-uploading. This updates behavior to prevent form submission while a fiel is uploading, and also ensures the file upload progress bar never shows a complete upload before teh fiel actually finishes, which currently happens frequently

Fiel upload in progress UI improvement

---

hail_search/queries/mito.py
hail_search/test_search.py
hail_search/test_utils.py

Variant hover over before:
After:
Variant search before this change used the GQ filter and excluded MITO variants. After the change, the GQ filter no longer applies to MITO variants even if it's included in the request. Here's a screenshot from debugging, see that `field` is `None` even though `min_qc` is included in the filters:

remove GC from MITO variant search and hover over

---

seqr/management/commands/deactivate_project_search.py
seqr/management/tests/deactivate_project_search_tests.py

Since there are some projects where search will not be available after the hail backend go live, we need a way to safely disable search in those projects beforehand

Deactivate project search command

---

ui/shared/components/panel/variants/Frequencies.jsx

(cherry picked from commit 38b4bbdb98883fc6909ba82d09db71b264c9084e)
Gnomad website have defaulted to V4 so the Gnomad V2 links are broken unless `dataset=gnomad_r2_1` query param is provided in the URL.

Fix gnomad v2 links

---

seqr/urls.py
seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
seqr/views/utils/orm_to_json_utils.py
settings.py
ui/pages/Project/components/ProjectOverview.jsx
ui/pages/Project/reducers.js
ui/pages/Project/selectors.js

Addresses a longstanding issue with slow loading for the RGP project page(~9 seconds). The major change is to stop returning all Samples as part of the project overview.
RGP currently has ~3500 active samples and ~50,000 inactive samples. On the project page, we use samples for the following:
- **All samples** to show the "Datasets" summary section, which shows all the samples/dataset types broken down by the number of samples loaded on each date
- Active samples to show the "Families/Individuals With Data" summary section (was using all samples but that was a bug, it should always have been active only)
- **All samples** for data export
- The first samples loaded for each family, to show on the family table an to sort it
- Active samples to display/sort/filter the family table
Returning …

Project overview performance

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reset_cached_search_results_tests.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py
seqr/views/utils/variant_utils.py

The variant lookup endpoint now completes in less than the max time for running a search on the pod, but its intermittently taking longer than the browser/django is allowing before showing a 504. While not as good as just succeeding the first time, caching the result means that if the user refreshes the page after a request fails, the response will be in the cache and can be shown to them. This is behavior analysts are used to for long-running searches, and is consistent with how searches generally behave

add caching for variant lookup

---

seqr/views/utils/orm_to_json_utils_tests.py

Hi! There's an assertion in the `test_json_for_saved_variants_with_tags` test that performs a `next(iter(<dictionary>))`, which for a dictionary has an indeterministic order. In our CI, sometimes this fails. One of the variants here contains the variantTag for an AIP variant, which gets formatted with `metadata → apiMetadata` causing this test to intermittently fail. 
https://github.com/broadinstitute/seqr/blob/2e0a222705369b2967464c54f131ed4965a1f6c5/seqr/views/utils/orm_to_json_utils.py#L441-L445
For this reason, I propose selecting the tag `VT1726961_2103343353_r0390_100` to look at the keys for.
Here are the keys by tag ID for the `variantTagsByGuid`:
```json
{
"VT1726961_2103343353_r0390_100": [
"metadata",
"createdBy",
"lastModifiedDate",
"searchHash",
"tagGuid",
"name",
"category", …
```

Update indeterministic assertion in test_json_for_saved_variants_with_tags

---

ui/shared/components/panel/variants/Annotations.jsx
ui/shared/components/panel/variants/Annotations.test.js

Our analysts/curators were a little confused when the Seqr variant search results did not return the Canonical nor MANE transcripts.  We subsequently added logic to highlight this in the UI.  We've had a fair bit of discussion around this and @drtconway in our group could can provide better context and why it's useful.  I initially thought of raising a discussion first but I think a PR is easier, just reject it if your group doesn't find it useful.

feat: Clearly show when variant transcript is not Canonical nor MANE

---

hail_search/queries/base.py
hail_search/queries/gcnv.py
hail_search/queries/mito.py
hail_search/queries/multi_data_types.py
hail_search/queries/snv_indel.py
hail_search/queries/snv_indel_37.py
hail_search/queries/sv.py
hail_search/web_app.py

This changes the control flow for recessive searches. In the search included in the linked ticket, this reduced the search time by over 60seconds on my local machine, from > 300 seconds that could not even complete on production to 245 seconds which can
Previously, we read in the entries table(s), filtered them to variants that were valid for either hom recessive or comp het, annotated and filtered them, and then at the end ran a filter for hom recessive only and a filter for comp het only to separate it out. What this instead does is that the entry table is initally filtered into 2 different tables, one for hom recessive and one for comp het, and then each table is independently annotated and filtered for the duration of the search.
Originally I did not go this route because it involved …

Recessive search split tables

---

hail_search/constants.py
hail_search/queries/base.py
hail_search/queries/multi_data_types.py
hail_search/web_app.py

This adds a few minor performance/control flow optimizations to avoid extra computations in proband only and duo families. However, the bulk of the performance savings come from setting the `use_new_shuffle` flag, which reduced the runtime of a problematic recessive search from 385 seconds to 230 seconds

No phasing comp het

---

seqr/fixtures/1kg_project.json
seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/hail_search_utils_tests.py
seqr/utils/search/search_utils_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/test_utils.py

Our fixture data only included mito data for an unaffected individual, and since we do not include fully unaffected families in most searches MITO data was being excluded in most of our test searches. This makes it really hard to test if MITO data for affected families would be sent for a particular search or not. This PR just changes the fixture data and all the cascading tests, there will be a follow up PR to change the behavior of when we do and do not include MITO data in searches

Better mito test data

---

ui/pages/SummaryData/components/VariantLookup.jsx
ui/shared/components/panel/variants/Variants.jsx

uses the main variant ui component that actually has IGV instead of the subcomponent that doesn't

use variant ui with igv

---

seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py
seqr/utils/search/utils.py

Improves search performance by adding additional prefiltering for which data types can be included in search. In particular, removes mito search from several places where no mito variants are possible

Better data type restrictions for searches

---

hail_search/queries/base.py

An AF of 1 is the max possible AF so in the UI setting a frequency to 1 is the same as saying "ignore this filter", but the hail backend is still applying it which is causing some weird behavior for certain deprecated populations

Skip unused frequency filters

---

deploy/kubectl_helpers/logs.sh
deploy/kubectl_helpers/port_forward.sh
deploy/kubectl_helpers/set_env.sh
hail_search/queries/base.py
hail_search/queries/snv_indel.py

This adds additional up-front prefiltering to improve performance for multi-project search. It also updates some of the `kubect_helper` scripts to make proxying to the hail backend locally easier

Additional prefiltering for multi rpoject search

---

hail_search/queries/base.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py

Allows the seqr app to set the max partitions in hail backend, so we can quickly iterate in dev and experimentally determine the optimal partition count

configure max partitions in seqr app

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/commands/reload_saved_variant_json.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reload_saved_variant_json_tests.py
seqr/utils/search/elasticsearch/es_utils.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py
seqr/views/apis/saved_variant_api.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/variant_utils.py

After new data is loaded, seqr allele frequencies (plus possibly other annotations) will be updated for all variants of the data type. This will cause the saved variants to be updated to stay in sync with the latest annotations

Reload saved variants after new samples loaded

---

hail_search/queries/base.py
hail_search/queries/snv_indel.py
hail_search/queries/sv.py

Reverts broadinstitute/seqr#3936
Having tested this in dev, even reading in just the single gene from the annotations table is too much for SNV_INDEL data

Revert "Multi project gene search redesign"

---

seqr/fixtures/1kg_project.json
seqr/views/apis/data_manager_api_tests.py

In the project overview we return all active samples plus the first loaded sample for each family. Because we were lazy, all our sample fixture data had the same loaded date so there was a family where sometimes it assigned an active sample as the "first loaded", but sometimes it chose the inactive sample as first leading to one extra sample being returned and causing the test to flap. This is resolved by setting a distinct loaded data for all the samples, so the same sample is always chosen as the first loaded

fix flappy test - deterministic first loaded sample order

---

hail_search/queries/base.py
hail_search/queries/snv_indel.py
hail_search/queries/sv.py

Reverts the previous reverting of a PR: https://github.com/broadinstitute/seqr/pull/3948
The optimization was worse the way it was written, but this moves the filtering to make it work better
The diff thats being added here not including the previously added coded being added back can be viewed here: 
https://github.com/broadinstitute/seqr/compare/7ae6c4bd0d196561b5d91d61c858c88f025411b9...multi-project-gene-prefilter?expand=1

Multi project gene prefilter

---

seqr/fixtures/1kg_project.json
seqr/views/apis/dashboard_api.py
seqr/views/apis/dashboard_api_tests.py
seqr/views/utils/individual_utils.py
ui/pages/Dashboard/components/ProjectEllipsisMenu.jsx

Current behavior in seqr is to show users the delete button and then throw an error when they try to delete the project. This changes the behavior to not show the button in the UI in the first place

Disable project delete UI

---

seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py

Attempting to reload saved mitochondrial variants threw an error due to an old representation of the mito chromosome that was not being properly converted

properly format mito chrom for variant id query

---

matchmaker/views/external_api.py
matchmaker/views/external_api_tests.py

If a MME match comes in and matches many submissions, we send one email per submission to let the users know. However, if any of those emails fail to send we combine those failures into one error which lists all the results that matched but does not make clear which submissions were correctly notified and which were not
Example of unclear notification: https://console.cloud.google.com/errors/detail/CNLmz4aq-YiVjwE;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=resolved-error

specify which notification failed when reporting notification error

---

ui/shared/utils/constants.js

corresponds to pipeline change in this [PR](https://github.com/broadinstitute/seqr-loading-pipelines/pull/713)

add clinvar pathogenicity to ui constants

---

seqr/views/utils/variant_utils.py

Adds better filtration for reloading saved variant json, to prevent errors such as this one that was triggered over the weekend: https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CPyKxOuL3qCBLA%22%0AlogName:%22stderr%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22seqr-project%22%0Aresource.labels.location%3D%22us-central1-b%22%0Aresource.labels.pod_name%3D%22seqr-check-new-samples-job-grch38-snv-indel-fvqzf%22%0Aresource.labels.container_name%3D%22seqr-check-new-samples-job-pod-grch38-snv-indel%22%0Aresource.labels.cluster_name%3D%22seqr-cluster-prod%22%0Aresource.labels.namespace_name%3D%22default%22;cursorTimestamp=2024-03-16T02:54:12.061140841Z;startTime=2024-03-16T02:24:42.061Z;endTime=2024-03-16T03:24:42.061Z?project=seqr-project

Better saved variant datset type filtering

---

seqr/fixtures/1kg_project.json
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reload_saved_variant_json_tests.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/utils/orm_to_json_utils_tests.py
seqr/views/utils/test_utils.py

The test fixture data has been messed up a for some time where the chrom/pos/xpos do not actually map to the variant ID due to an old typo. This has propagated across a lot of tests at this point, but makes testing things difficult as. you get a different variant ID depending on how you compute it, which can't actually happen with real data

update fixture data variant IDs

---

.github/workflows/hail-search-persistent-volume-snapshot-release.yaml

reference_genome/datset_type/version are still required here (🤦) to keep the check-new-samples job running.

Include both dataset version and volume handle

---

seqr/fixtures/users.json
seqr/management/tests/detect_inactive_priveleged_users_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/airflow_utils.py
ui/pages/DataManagement/components/LoadData.jsx

Ads the option to load SNV/INDEL data from the UI, and adds a check with airtable to only load projects that are ready for loading in airtable, and only load the subset of families that are actually updated. When this goes live it should work redundantly with the current airtable checks in airflow (so no issues should arise) and then after this is live those can be safely removed
Project dropdown UI:

UI snv indel loading

---

ui/shared/components/panel/variants/Transcripts.jsx
ui/shared/components/panel/variants/Transcripts.test.js

The api endpoint associated with this button checks that users have edit permission on the project, but the button is shown to all users. This updates behavior so only users with permission see the button

only show update transcript button to users with edit permission

---

seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py

There should never be a case where the load_data endpoint fails to find the file. However, it is currently happening, and while I still do not know why I do know that when it does happen it should return a human readable error and log an informative error to alert the seqr engineers, instead of returning an incomprehensible unhandled error

better error handling when rna temp file missing

---

seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py

For RNA loading we parse the input file and split it into one file per sample, and then we dispatch one request per sample to load from each subset file in order to achieve parallelism and prevent server timeout (actually parsing and then writing all the data from the file in one request takes way longer than the browser can handle). 
However we have 2 running seqr pods, so all the sample subsets get written into the filesystem of one pod, but then roughly half the follow up requests get routed to the other pod and that pod's filesystem does not have the expected file. This PR therefore moves all the files off of the pod and into GCS so both pods will have access to them

Multi pod rna loading bug

---

ui/pages/Project/components/PhenotypePrioritizedGenes.jsx
ui/pages/Project/reducers.js
ui/shared/components/panel/variants/VariantGene.jsx

If a user goes to the saved variants/ variant search page and then goes to the family page and views phenotype prioritized data, the data has been loaded just for the genes in the search page which was causing it to not load all the data and instead only show a subset. This updates the code to check and ensure all the data is loaded and fetch if not. 
Once this issue was fixed, the genes for the laoded data had all the locus list info loaded but the other genes did not which was making the table look weird, so I also updated the display to explicitly not show locus lists in the prioritized phenotype table

load all phenotpye priorities after viewing variant page

---

seqr/urls.py
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py
ui/pages/Report/Report.jsx
ui/pages/Report/components/FamilyMetadata.jsx
ui/pages/Report/components/VariantMetadata.jsx
ui/pages/SummaryData/SummaryData.jsx
ui/pages/SummaryData/components/IndividualMetadata.jsx
ui/shared/components/table/LoadReportTable.jsx

Reverts broadinstitute/seqr#4015
The ticket requests that certain reports be made available to local installations by default. Since local installations do not have an analyst role and the reports tab is only show to analysts, we moved the reports from the "reports" tab to the "summary data" tab (which is available to all users). However, the unintended consequence of this is it meant these reports were also made available to AnVLl users on the Broad's seqr instance. AnVIL projects can not be configured to work for these reports, and the support burden on the seqr team is too high to try and get these to work. Therefore, we are reverting this change entirely and will instead make the reports available to local installs by making updates to the reports tab access

Revert "Make metadata reports available to local users"

---

CHANGELOG.md
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/test_utils.py
ui/pages/Report/Report.jsx
ui/shared/components/page/Header.jsx

In local installations there is no analyst role by default but there is a PM role. Therefore in order to make these reports available to local users we are updating the report tab to show some relevant reports to PMs as well as analysts. This will have no impact on the Broad seqr instance, as all our PMs also have analyst permissions.

Local install reports

---

seqr/views/apis/family_api.py
seqr/views/apis/individual_api.py
seqr/views/apis/project_api.py
seqr/views/utils/project_context_utils.py

This PR optimizes the generated SQL queries for a couple of the slower project detail endpoints. Overall, changes work to reduce table joins where possible and reduce duplicating queries to the same table (i.e. get all data in one query instead of multiple). 
A. note on how this sort of optimization is done: django has pretty good debug tools for this. I change the `ENABLE_DJANGO_DEBUG_TOOLBAR` setting in settings.py to True which enables it. The "gotcha" for this tool is it will only profile requests thqt return HTML, so for whatever API endpoint I want to profile I replace the final return statement with the following, and then access the API endpoint directly in my browser 
```
from seqr.views.react_app import render_app_html
return render_app_html(request, include_user=False)
```
The …

Optimize SQL queries for project page performance

---

seqr/migrations/0064_alter_phenotypeprioritization.py

This migration is actually taking longer than the timeout for the seqr pod in dev, causing it to terminate before the migration can complete. This improves performance by doing one query to map PP models to individuals, instead of one query per model

improve mgration performance

---

seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py

There is search backend logic to compute the aggregated counts of variants per gene per family. However, if all the variants for a query have been fetched and are in the redis cache we compute the breakdown in python, instead of querying the backend. It turns out the logic for the breakdown is different between the 2 backends, and therefore we need to update the logic for computing the breakdown in the cache to be backend specific as well

search backend specific logic for gene breakdown

---

reference_data/management/commands/utils/download_utils.py
reference_data/management/commands/utils/update_utils.py
reference_data/management/tests/test_utils.py
reference_data/management/tests/update_gencode_tests.py

The GenCC download no longer supports HEAD requests. Since these are only used for an optimization to prevent re-downloading a file this is not a blocking change, we just need to update error handling to allow loading to prceed

fix update_gencc command

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/commands/reload_saved_variant_annotations.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reload_saved_variant_annotations_tests.py
seqr/utils/search/hail_search_utils.py

Currently all the annotations for saved variants are automatically updated whenever new data is available in seqr. However, there will be times when we may update the annotations table without loading new samples (i.e. for new VEP table) so having the ability to sync annotations with the backend is useful (and also can be useful during local development)

Job to update savedvariant annotations

---

seqr/views/apis/summary_data_api_tests.py
seqr/views/utils/airtable_utils.py

Unhandled errors in seqr alert the engineers, but in the case where airtable is misconfigured theres no need for a seqr engineer - any user getting this error would either be a PM or would be an internal user who would know to reach out to the PMs with airtable issues, and the error is sufficiently user-friendly and descriptive. Therefore continuing to alert the engineers is just unnecessary alert fatigue

do not raise unhandled error on airtable mismatch

---

ui/shared/utils/constants.js

Updates the search UI to match the newly available transcript consequences. No change to the search backend neccessary for these filters to work. 
Note that this code is not conditional, and will update for local installs on elasticsearch as well. There are already many search consequence options in the UI that are not actually available in search (theres an open bug on this) and a couple consequences that were in the data but not available in the UI. Therefore I do not think these changes will significantly degrade behavior for local installs, and adding conditional logic to the UI for which set of consequences to show did not therefore seem to be worth it.  
This code is against a branch and will be rleeased to production after the updated VEP is live

Vep consequence updates

---

hail_search/queries/base.py
hail_search/queries/snv_indel.py
hail_search/queries/snv_indel_37.py

This changes the class inheritance for the `SnvIndelHailTableQuery` and `SnvIndelHailTableQuery37` so that 38 inherits form 37 instead of vice versa. This will make some of the refactors needed for the new VEp annotations that are 38 only easier to implement.

swap snv_indel search class inheritance

---

seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/react_app_tests.py
seqr/views/utils/test_utils.py

Updates the behqvior of our Local/Anvil test cases that are used extensively in the repo to also handle conditionally testing the search backend. Currently, we have a few places where we add some nested `with mock.patch` to test behaviors, but it is not as robust and makes it difficult to add additional backend-specific tests (which I need to do for some of the upcoming VEP work).

Search backend conditional unit tests

---

seqr/views/apis/analysis_group_api.py
seqr/views/apis/analysis_group_api_tests.py

If a user creates an analysis group by uploading a file, there is an extra field in the POST body that should be ignored

remove unused param from create analysis group body

---

seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py

AIP upload is ambiguously mapping individuals to families/ projects, so reguire explicit whitelist for projects

Aip family mapping

---

seqr/urls.py

resolves deprecation warnings before upgrade
```
/Users/jklugher/codebase/seqr/seqr/urls.py:361: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
urlpatterns = [url('^status', status_view)]
```

resolve django deprecation warnings

---

settings.py

logged request_origin: https://seqr-dev.broadinstitute.org
expected CSRF_TRUSTED_ORIGINS: ['https://seqr-dev.broadinstitute.org/', 'http://seqr-dev.broadinstitute.org/']

remove trailing slash from BASE_URL in CSRF_TRUSTED_ORIGINS

---

ui/pages/Project/components/FamilyTable/IndividualRow.jsx

We had a generic configuration for the modals we show in the individual row, but we have since cleaned up that code so there is only one modal but we left the configuration as a constant, instead of inlining the code. In doing an audit of how we show RNA data in the UI I realized this was causing us to do unnecessary checks for sampleId, and in general it makes it harder to read the code and see what is being rendered

clean up phenotype prioritization modal config

---

seqr/views/apis/data_manager_api_tests.py

We do not actually test the behavior when the pedigree file contains more entries than the sample subset. Since that behavior is going to change, I wanted to add a test case for it

add test case where subset is not whole pedigree

---

seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py

We are getting a javascript error because certain family fields are missing in the response for families with no individuals. This refactors how we populate those fields so they are always filled out for all families

properly populate individual aggregate fields for families with no individuals

---

ui/pages/Search/VariantSearch.jsx
ui/pages/Search/components/PageHeader.jsx
ui/pages/Search/selectors.js
ui/pages/SummaryData/components/Hpo.jsx
ui/redux/rootReducer.js
ui/redux/selectors.js
ui/redux/utils/configureStore.js

The HPO summary page created search links that put the projects and families for the relevant families directly in the URL. This ran into browser URL size limits if there were too many families, so we disabled search over that number. Since users want to do searches in more families than the limit, this rearchitects that link to instead save the families to the state/ local storage and put a hash in the URL (similar to the behavior we use for running searches)

No max families for hpo search

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/commands/reload_saved_variant_json.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reload_saved_variant_json_tests.py
seqr/views/apis/saved_variant_api.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/utils/variant_utils.py

Project in seqr can be manually updated to a new genome version, and when this happens we attempt to lift all the saved variants, but in some edge cases that fails and we have saved variants associated with a different genome version than the project. When that has happened, we should no longer try to sync the saved variant json with the data in the search backend, as it would sync with the wrong variant/ have invalid coordinates for that build

Reload saved variant genome build

---

deploy/LOCAL_DEVELOPMENT_INSTALL.md
deploy/LOCAL_INSTALL.md
test_local_deployment.sh

Apparently docker has updated the syntax you use for running docker-compose commands: https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose

update to latest docker compose syntax

---

ui/shared/components/panel/search/FrequencyFilter.jsx

Same philosophical fix as https://github.com/broadinstitute/seqr/pull/4262/files#r1693453061 but this time actually removes all the unsupported frequencies instead of leaving them unchanged

actually remove deprecated populations on header freq change

---

deploy/docker/seqr/entrypoint.sh
hail_search/queries/mito.py
seqr/fixtures/variant_searches.json
seqr/management/tests/reset_cached_search_results_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/orm_to_json_utils_tests.py

Django's `loaddata` command will update data in the database based on fixture json. If PK is specified, Django will create a model with that pk if none exists, or will update the existing model if it does. There is no harm in running the command if nothing changes
This PR encodes our current saved searches into source control with no change

Shared saved searches in source control

---

seqr/views/apis/data_manager_api.py
seqr/views/apis/igv_api.py
seqr/views/apis/igv_api_tests.py
seqr/views/utils/dataset_utils.py

IGV JS's reference files are now returning 403 errors, but proxying the headers fixes this issue

Igv proxy error

---

seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py
seqr/views/utils/airtable_utils.py
seqr/views/utils/test_utils.py

While working to make the data loading interface work for local installs I discovered we are not robustly checking and error handling when airtable requests are made while airtable is not configured. This adds a validation when starting up airtable sessions to sanity check that airtable is configured, and then adds explicit checks where needed to avoid running into that case

Better airtable enabled checks

---

ui/shared/components/panel/family/constants.js

our proxy is likely not necessary any more for IVG track requests!
use new sources for all ivg tracks from [here](https://igv.org/genomes/genomes.json)
verified locally that IGV loads for 37 and 38 variants

skip proxy for all tracks

---

hail_search/constants.py
hail_search/queries/base.py
hail_search/queries/mito.py

Improves large gene search performance in a couple ways:
- Allows for a larger number of clustered intervals (meaning far fewer variants outside of the true intervals are included)
- Reduces the number of partitions. Hail does not allow for specifying both intervals and number of partitions at table read time, but the number of partitions based on the large number of intervals is too high and reduces performance. While a full `repartiton` is far too slow to be helpful, `naive_coalesce` reduces the number of paritions quickly and does not seem to introduce any problems with how balanced the partitions are

better interval filtering and partitioning

---

ui/pages/SummaryData/components/VariantLookup.jsx
ui/pages/SummaryData/selectors.js

In the variant lookup UI, groups cases by their VLM contact so users will only send one email per contact, instead of potentially sending identical messages to the same researcher multiple times
Example where 2 collaborators have the variant, one with 3 cases and one with 1.

show vlm families grouped by contact email

---

.github/workflows/dev-hail-search-release.yaml
.github/workflows/dev-release.yaml

Per [this pr](https://github.com/broadinstitute/tgg-helm/pull/109), the `tag` will be nested under `seer-platform` going forwards.
Note: this only updates the `dev` actions.

Update action seqr platform

---

hail_search/queries/mito.py
hail_search/test_utils.py
seqr/views/utils/test_utils.py
ui/shared/components/panel/variants/Annotations.jsx

Since MITO is not supported for local installs we do not need to maintain backwards compatibility for elasticsearch and can therefore fully deprecate the old syntax for this field

remove mito highConstraintRegion

---

seqr/utils/search/add_data_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/utils/airflow_utils.py
seqr/views/utils/individual_utils.py

Updates the validation logic for AnVIL loading so only families with new/updated samples are loaded and complete families can be skipped for data loading

Anvil allow partial project loading

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/views/utils/airtable_utils.py

We create PDOs for sex/relatedness failures buy cloning all the fields, but this means if the PDO being split does not have loading status anymore the new PDO does not either, so set it explicitly

explicitly set PDO status for sex/relatedness PDOs

---

reference_data/management/commands/update_all_reference_data.py
reference_data/management/tests/update_all_reference_data_tests.py

This change means the first time update_all_reference_data is run it will fully populate the reference data db, but on subsequent runs it will be skipped. This means if it runs after kubernetes install it will work correctly the first time and then for all future times nothing bad happens

do not reset gencode from update_all_reference_data

---

deploy/LOCAL_INSTALL.md
docker-compose.yml

The init script we added for postgres is not actually available for local installs unless they clone the whole seqr repo which is not the recommended approach. While a little messy this adds a couple of lines to the manual instructions to make sure the file is available locally

Local install - postgres init

---

ui/shared/components/panel/variants/VariantGene.jsx

The gene search link on the variant lookup page causes errors, analysts agreed its confusing to have there and would rather it was removed. 
Search error: https://console.cloud.google.com/errors/detail/CL2Ln7jdy_jwLw;locations=global;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=resolved-error

hide gene search link on variant lookup page

---

seqr/utils/search/add_data_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/family_api.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/pedigree_info_utils.py
ui/pages/Project/components/edit-families-and-individuals/BulkEditForm.jsx

Updates seqr in a few places to try and reduce instances of families with no affected individuals:
- when  bulk editing individuals, validate at least one individual in family is affected
- disable ability to create empty families (families are already created by creating individuals for them)
- add additional check when generating loading pipeline to fail loading request when attempted with an unaffected family

Require affected family members

---

hail_search/queries/base.py
hail_search/queries/mito.py

When building the VLM I discovered that the approach we were using to look up variants in the hail backend, which is to  create a key-table of locus-alleles and then use `query_table` to just read in the relevant rows, is actually substantially slower than reading in the table directly with the intervals set to the one base pair interval of the variant itself and then filtering for matching alleles. Testing on an GRCh37 lookup the time went from 32 seconds to 16 seconds, and GrCh38 is actually a bit slower the 37
The `query_table` approach is still needed for SV lookup, as SV tables are not keyed by locus

do not use query_table for variant id queries

---

hail_search/queries/base.py
hail_search/queries/mito.py
hail_search/queries/sv.py

This refactors how we add the genotype-level data from all seqr projects. Previously we were joining all the project tables to the annotation table and then doing a single take aggregation, this changes the behavior to separately aggregate the annotation data and genotype data and then combine them after the fact. This change does make lookup a couple seconds slower (although nowhere near undoing the performance gains from https://github.com/broadinstitute/seqr/pull/4518) but is a necessary precursor to the VLM-related feature of including genotypes from projects on different genome builds

separate agg for variant lookup project data

---

seqr/views/utils/airflow_utils.py

We encountered a bug in this connection between the UI and airflow resulting in an in-progress DAG being over-written because it was in a "queued"/"scheduled" state rather than "running".  This expands the check to include all non-completed airflow statuses.

Improve status designation for in-progress DAG

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

Returns one error message per project with the updated PDO summary includedo once instead of. one message per project-check with the pdos included every time

single loading error per project

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/communication_utils.py
seqr/utils/search/add_data_utils.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/dataset_api_tests.py
seqr/views/utils/dataset_utils.py

email notification for RNA loading did not include the project name/URL because we were sending it with a url formatted for slack instead of regular html. Since most notification include links to projects and this is an easy mistake to make I updated the `send_project_notification` helper function to handle slack as well as email notification and to handle constructing the URL for each in the helper instead of having the URL passed in by the calling function. This fixes the bug and also means that this is less likely to happen again in the future. In the process of unifying the functionality there are some slight differences to some of the slack/email messages being generatdd by this helper but they should all be either improvements or at worst neutral changes

shared notification url formatting

---

seqr/management/commands/check_for_new_samples_from_pipeline.py

When reloading saved variant annotations fails at the end of the check samples job we report that the whole jb failed which is not true. Its i  more accurate to have the job succeed but log an error which will alert developers that this step failed and needs to be re-run. Inspired by this failure: https://the-tgg.slack.com/archives/G01EEU8PR35/p1737044853064989

add error handling for reload annotations failure

---

seqr/utils/communication_utils.py
seqr/views/apis/dataset_api_tests.py
seqr/views/utils/test_utils.py

When we tried to add extra detail to the error log on email failure it caused an error to be re-raised because it could not properly json serialize the log. We were missing this in our tests because we were mocking the logger. Our tests by default log to a captured stream so you can test what is actually logged without mocking the logger at all, and changing the test to no longer mock the logger caused the bug to replicate in our tests

handle email error log issue

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/utils/export_utils.py

draft pr while I work on tests!

report pipeline validation errors from seqr

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

Fixes bugs with running the check samples job locally and adds unit tests and full support. Primary differences between running locally and at Broad are access to airtable and special slack and email formatting for external anvil projects

Local support for check samples job

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

The latest changes to the check samples job to include validation results are failing because the new `ls` command output includes the directory name as well as all the files in the directory and the regex no longer works

properly handle regex for directory name

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

This moves the reporting for validation errors to after the checking for successful samples so issues with validation n the future will not block data loading, and also adds some resiliency for malformed validation error json

Validation reporting resliancy

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/utils/airtable_utils.py

The check samples test currently mocks out several different loggers and then tests them independantly. This removes those mocks and instead uses the built in test case log capturing to test that all logs look as expected. This makes the test more maintainable (when making a feature change I was really struggling to get the log tests to work again). As a bonus, it caught an edge case where error detail could not be properly json encoded and in a real world case would not have logged properly!

Check samples test logs

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/utils/airtable_utils.py

The check samples test was recently updated to have a separate local and anvil test case that run separately. However, when that functionality was added we did not split out the parts of the existing tests for using local vs gs file paths, so we ended up testing the behavior of local and gs file in both local and cloud deployments, in other words we are running 4 test permutations instead of 2. In addition to being unnecessary, this also makes updating these tests difficult and is an antipattern to how we test behavior elsehwere in seqr. This PR splits the test so the local test tests local files and the anvil/cloud test tests gs files

Clean up check samples test

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/communication_utils.py
seqr/utils/search/add_data_utils.py

When an anvil project fails validation, seqr will automatically email the project owner with the list of failures. It will also post a message to our slack channel and update our airtable loading tracker. This means that when validation fails our team does not need to do *anything* to resolve it until/unless the user emails us back to follow up on those errors!

Report loading validation failure to anvil

---

seqr/views/apis/data_manager_api_tests.py

We were explicitly mocking file interactions separately for gs and local files in some of the data loading tests instead of using the shared helper functions in the class to correctly mock file interactions for the given test. This makes updating these tests when those interactions change difficult, so before I do that I decided to clean up the tests

Data manager test cleanup

---

deploy/LOCAL_INSTALL_HELM.md

Ok!  This is fully working now!  
Logs on the local pipeline worker:
```
===== Luigi Execution Summary =====
Scheduled 5 tasks of which:
* 5 ran successfully:
- 1 CreateDataprocClusterTask(reference_genome=GRCh38, dataset_type=SNV_INDEL, run_id=20250122-154349)
- 1 RsyncToSeqrAppDirsTask(...)
- 1 RunPipelineOnDataprocTask(...)
- 1 TriggerHailBackendReload(...)
- 1 WriteSuccessFileTask(...)
This progress looks :) because there were no failed tasks or missing dependencies
```
And the successful [dataproc job](https://console.cloud.google.com/dataproc/jobs/RunPipelineTask-20250122-154349/monitoring?region=us-central1&inv=1&invt=AbnioQ&project=seqr-project)
I also confirmed search worked!

locall install helm dataproc

---

seqr/utils/search/add_data_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/pedigree_info_utils.py

The helper functions we use to validate pedigrees involve a lot of code duplication, in particular in the way that they look up potential existing individuals in the database. In order to implement https://github.com/broadinstitute/seqr/issues/4580 we need better shared utilities for validating samples which was hard to do with the existing mess of validation. This cleans up the validation code and also abstracts out the logic used for validating the search sample subset into a single helper function.
This PR contains essentially no behavior changes- the only exception is that previously we did 2 steps to validate AnVIL loading requests and thats now done in one step, so certain requests now include more validation falures on the first pass instead of some failures and then more failures …

Pedigree info validation clean up

---

seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py

We currently do not allow local installs to specify a dataset type in the loading UI, but we have never reflected that difference in the backend. For the upcoming callset validation changes it helps to simplify the cases we need to support to those that are actually possible in the app, so this restricts the code path for local installs to only be able to load VCFs. This also updates the tests to be mroe representative of the actual request data thats possible

Disable local dataset support

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/commands/reload_saved_variant_annotations.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/reload_saved_variant_annotations_tests.py
seqr/views/utils/variant_utils.py

Reloading all variant annotations has been failing. I was playing around with the page size but made it too big. This resets that and also adds better support for incrementally updating saved variants by chromosome instead of trying to load everthing first and then update everything

Annotation reload improvement

---

hail_search/queries/base.py
hail_search/queries/mito.py
hail_search/queries/sv.py
hail_search/test_search.py

SV search is no longer working for an all-project single gene search. This is because unlike with other data types we can not prefilter the project tables to a single gene. However, the full SV_WGS is only ~500,000 rows (roughly the same size as a SNV_INDEL WGS project table) and can be fully read into hail. This therefore refactors SV gene searches to first read in the annotations table and prefilter the project tables on that, instead of vice-versa

Sv gene search

---

.github/workflows/unit-tests.yml

Looks like we missed this notice that we had to update by February 1 😨 
https://github.com/actions/cache/discussions/1510https://github.com/actions/cache/discussions/1510

update github actions/cache version

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/search/add_data_utils.py
seqr/views/utils/dataset_utils.py

We ran into a bug in the check samples job when there are no new samples being loaded. This PR does the following:
- Fixes that bug
- Changes the behavior for reloading saved variants to also reload previously loaded families (when adding a unit test to cover this case I discovered this was not happening and we want it to)
- Splits out the logic into more localized try/except blocks with clearer errors so that future errors will be clearer about where they are happening, and also where possible will allow other unrelated steps to run even where some upstream steps fail

Check sample reload only bug

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/utils/variant_utils.py

Improved performance in the check samples job and elsewhere by using a bulk update instead of saving each model individually

use bulk update for updating project variants

---

panelapp/migrations/0003_panelapp_aus_domain_migration.py
seqr/fixtures/1kg_project.json
ui/shared/utils/panelAppUtils.test.ts

Reference discussion: https://github.com/broadinstitute/seqr/discussions/4623
This script bulk replaces domain name in table field `panelapp_palocuslist.url` from `https://panelapp.agha.umccr.org` to `https://panelapp-aus.org`.  This allows subsequent runs of [import_all_panels.py](https://github.com/broadinstitute/seqr/blob/master/panelapp/management/commands/import_all_panels.py) script to not create new panels.
To run this script: `python manage.py migrate panelapp`
The Django admin script [import_all_panels.py](https://github.com/broadinstitute/seqr/blob/master/panelapp/management/commands/import_all_panels.py) should be run with new url from Tue, 25th Feb onwards.
`python manage.py import_all_panels --label AU https://panelapp-aus.org/api/v1`

DB migration for PanelApp AU domain name change

---

ui/shared/components/panel/variants/VariantGene.jsx

If a variant is tagged from the lookup page it will have `lookupFamilyGuids` in the saved variant json. When that saved variant is then rendered on the saved variant page the conditional logic designed to disable the gene search link from the lookup page fails. This fixes the logic to require the presence of `familyGuids` instead of the absence of  `lookupFamilyGuids`

show gene search links for variants that were tagged on the lookup page

---

hail_search/queries/sv.py

SV variant lookup performs a search with the padded_interval filter and not the standard interval filter. Because of this, the optimized flow for filtering annotation first was not being properly triggered. This tweaks setting the flag for the optimized flow to also factor in padded_interval

use interval prefilter logic for search with padded interval

---

hail_search/queries/base.py
hail_search/queries/sv.py
hail_search/test_search.py

Fixes a bug when an empty structural type list is passed in the search body (which occurs when a user checks and then unchecks an option). Also improves performance for multi project SV gene search

SV gene search improvement

---

reference_data/management/tests/update_omim_tests.py
reference_data/models.py

A record was added to OMIM last week that broke our parsing script. Since we only use OMIM records in seqr that have either a gene or phenotype associated with them, I updated the logic to skip rows with neither and avoid parsing this row. 
Note that to prevent merge conflicts I have branched this off of my open reference data refactor PR, so that will need to be merged before this fix can be released: https://github.com/broadinstitute/seqr/pull/4706

Fix parse Omim record with no position

---

.github/workflows/prod-vlm-release.yaml

The latest release included a working version of the VLM that has been successfully tested on dev and can connect to another node, so at this point the manual overhead of managing releases does not feel worth it. Adding this job means all future VLM changes will be released the same way other seqr apps are, which is what we want at this point

add job for prod vlm release

---

hail_search/test_utils.py
seqr/fixtures/1kg_project.json
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/report_api_tests.py

We are having trouble running all project comp het searches with combined SVs and SNV_INDEL data. This change splits those queries under the hood into 2 searches instead of 1, running all of the WGS sample in one search and all of the WES samples in another. Since we will not have a project with both WES and WGS for SVs in the same project on the hail backend this will only impact multi project searches with SVs, and since those searches are currently timing out any inefficiency introduced by waiting on 2 searches is better than being unable to run the search at all.
The reason this is a logical way to speed up the searches is that the SV data is stored separately for WES and WGS so the queries are running sequentially, and then the joins with SNV_INDEL data for the comp hets are …

SV multi project comp het performance

---

hail_search/queries/base.py
hail_search/queries/multi_data_types.py

When searching for comp het pairs across data types we currently read in loads of projects that we don't end up using. In the linked ticket's WES search we load SNV_INDEL data for 93 projects even though only 70 of the projects even have SV data and of those only 10 projects have possible matched variants. This changes the loading logic so that for comp-het only searches only those 10 projects would be read in for SNV_INDEL, and for recessive searches all the families will be read in initially but the comp het table will be filtered to that subset before computing pairs
This also takes advantage of the changes in https://github.com/broadinstitute/seqr/pull/4725 that split searches by sample type so there will never be multiple SV data types in the same hail backend search so this PR …

Multi data type comp het search optimization

---

hail_search/queries/base.py

We [added support ](https://github.com/broadinstitute/seqr/pull/4744)to have regulatory and motif consequences allowed for secondary annotations, but this introduced a bug where pathogenicity overrides, which are only supposed to apply to primary annotations, are also applied to secondary. This PR fixes that bug by no longer passing through pathogenicity to the secondary filter

do not allow clinvar override for secondary annotations

---

seqr/fixtures/1kg_project.json
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/dashboard_api_tests.py

when checking if a user had any pending loading projects, we excluded any projects that have any loaded data. which means if a user had successfully loaded data to a project and then requested more data at a later date we would not consider that project to be pending even before the additional samples completed. This changes the logic explicitly check whether there are any families in the "waiting for data"state

update logic for determining pednding loading project

---

.github/workflows/unit-tests.yml
clickhouse_search/migrations/0001_initial.py
clickhouse_search/models.py
settings.py

The new helm chart major version provided an option to set the data directory (which was previously not provided).  This hopefully lets us follow the pattern we set previously with the `/var/seqr/...` directories.

Update ClickHouse default data directory.

---

ui/shared/components/panel/variants/Variants.jsx

There is a bug with compound hets js where when you click the main gene to open the modal it opens 2 modals on top of each other, and GTEX was being rendered in the back modal but not the front modal. Correctly setting the modal ID fixes this issues and ensures only 1 modal is opened per gene link and thus GTEX displays correctly

prevent duplicate gene modals for comp hets

---

clickhouse_search/search.py
seqr/utils/redis_utils.py
seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py

Search results are cached in redis, and since clickhouse sorting is done in python and not at the database level we can add an optimization that if the results are already cached with a different sort we can sort the existing cached results without querying the database

Clickhouse use cached unsorted

---

clickhouse_search/migrations/0009_materializedviews_and_dictionaries.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/vlm_utils.py

VariantMatcher has now implemented a compliant VLM spec and we are turning on that connection. In testing it, I found  2 issues with how we are currently parsing the VLM responses:
1) The dev MyGene2 connection had added an incorrect extra level of nesting in their handover response so when I built the parsing I built it to work with that incorrect schema. I have now confirmed that none of the nodes have this error in production anymore (including seqr)
2) VariantMatcher formats the result set IDs slightly differently that MyGene2, in part because VariantMatcher only has 1 possible db in its result set while MyGene2 actually has 2. Both formats are technically valid in our API spec (😭 ) so I have updated our parsing to be tolerant of both

fix vlm response parsing

---

.github/workflows/unit-tests.yml
clickhouse_search/backend/base.py
clickhouse_search/models.py
deploy/docker/seqr/entrypoint.sh
seqr/views/status_tests.py
settings.py

this is a very basic implementation of multiple users for clickhouse - let me know if you have any objections to the approach.

set different clickhouse credentials for migrate and app use

---

seqr/management/commands/reload_clinvar_all_variants.py
seqr/management/tests/reload_clinvar_all_variants_tests.py

A few small bug fixes:
- Filter variants where ref and alt alleles are equal.  These are present in the VCF with alt allele of "." and we're filtering them on import.
- The XML tree for conditions got spliced incorrectly when making the unit tests and is incorrectly nested.

chore: a few small clinvar bug fixes.

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/management/tests/lift_project_to_hg38_tests.py
seqr/utils/search/add_data_utils.py
seqr/utils/search/utils.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/variant_search_api.py
seqr/views/utils/test_utils.py

Updates our unit test fixtures to use clickhouse instead of hail search as the default backend for testing Non-local functionality. This does not actually decrease coverage for hail search functionality, and allows us to test the clickhouse-specific functionality for saved variants when it is added

use clickhouse as default backend for non-local unit tests

---

seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py

Since the variant lookup page allows users to put in a free text variant ID, we need better validation that the ID we are proxying to the VLM is valid. Looking through the logs I found a case where MyGene2 was returning an error because we had passed along a totally invalid variant. Adding this validation will prevent undo alert fatigue from the VLM (any time a request does not return a 200 we get alerted)

add allele validation before querying VLM

---

clickhouse_search/backend/fields.py
clickhouse_search/test_utils.py

In the hail backend this is handled automatically with how aiohttp encodes the json for the http response, but in django this is throwing an error

fix json encoding for SVs with null genes

---

clickhouse_search/management/tests/set_saved_variant_key_tests.py
matchmaker/views/external_api_tests.py
seqr/fixtures/1kg_project.json
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/summary_data_api_tests.py

The human readable family id and integer db id were identical in our test data which made this bug hard to detect, so in addition to fixing the bug I also updated the fixture data

Family id error message

---

clickhouse_search/search.py
clickhouse_search/search_tests.py
seqr/utils/search/elasticsearch/es_search.py
seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/utils.py

VLM will return counts across genome builds, but currently variant lookup is buggy when trying to return results from both builds. This fixes a bug in the case where the variant is present on both builds, and also adds explicit liftover in the case where it is absent from the requested build so we can check the other build. For this new liftover I abstracted the existing litover code we had set up to run on elasticsearch - pyliftover is already configured in our repo and is a much more lightweight solution than setting up all of hail just to run liftover

Fix variant lookup across genome builds

---

seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/search_utils_tests.py
seqr/utils/search/utils.py

The way the 2 backends handle caching is very different. The current control flow attempts to share as much code as possible between the 2 but this just leads to tons of backend specific branching that makes it very hard to read/maintain. This PR explicitly splits the caching logic between backends so the behavior for each backend is much clearer

Cache cleanup

---

ui/pages/DataManagement/DataManagement.jsx

We previously has  data manager pages that were airflow-specifc (delete dag triggering) and local-install-specific (pipeline UI), but now that airflow is deprecated those pages should all be avaiable for both local and non-local

enable all clickhouse data management pages

---

seqr/management/commands/deactivate_project_search.py
seqr/management/tests/deactivate_project_search_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
ui/pages/DataManagement/components/TriggerSearchDataUpdatePages.jsx

After [enabling the trigger delete data commands for local users](https://github.com/broadinstitute/seqr/pull/5037), the fact that  there is also a separate manage command or manual sample deactivation that needs to be done as well is not intuitive and would lead to user error. The solution is to just move sample deactivation directly into the trigger endpoint behavior

Delete search functionality cleanup

---

deploy/docker/seqr/Dockerfile

I updated the python version for the build image but not the runtime image. unsurprisingly, this does not result in a valid docker image

update python version for runtime image
