broadinstitute/seqr

settings.py
xbrowse_server/api/urls.py
xbrowse_server/base/management/commands/add_individuals_to_phenotips.py
xbrowse_server/base/management/commands/add_individuals_to_project.py
xbrowse_server/base/management/commands/add_project.py
xbrowse_server/base/management/commands/add_project_to_phenotips.py
xbrowse_server/base/views/family_views.py
xbrowse_server/phenotips/utilities.py
xbrowse_server/phenotips/views.py
xbrowse_server/sample_management.py
xbrowse_server/staticfiles/js/coverage.js
xbrowse_server/staticfiles/phenotips_integration/phenotips_integration.css
xbrowse_server/staticfiles/phenotips_integration/phenotips_integration.js
xbrowse_server/templates/base.html
xbrowse_server/templates/family/family_home.html
xbrowse_server/templates/javascript.html
xbrowse_server/urls.py

Feature phenotips integration 0.001

---

xbrowse_server/base/management/commands/migrate_analysis_status.py
xbrowse_server/base/models.py
xbrowse_server/base/views/family_views.py
xbrowse_server/base/views/project_views.py
xbrowse_server/decorators.py
xbrowse_server/json_displays.py
xbrowse_server/templates/client_templates/base.html
xbrowse_server/templates/client_templates/family.html
xbrowse_server/templates/family/family_home.html
xbrowse_server/templates/family_edit.html
xbrowse_server/templates/project/add_gene_list.html

Similar to notes and tags, keep track of the username + date for analysis status changes.

Feature track analysis status changes

---

xbrowse_server/base/forms.py
xbrowse_server/base/management/commands/migrate_causal_variants_to_variant_tags.py
xbrowse_server/base/models.py
xbrowse_server/staticfiles/js/base/basic_variant.js
xbrowse_server/templates/client_templates/family.html
xbrowse_server/templates/family/family_home.html
xbrowse_server/templates/project.html
xbrowse_server/urls.py

beginning of fix for https://github.com/macarthur-lab/seqr/issues/186

refactor causal variants to use tags

---

xbrowse_server/base/management/commands/add_project.py

Fix issue #215 - help not showing when no arguments provided to add_project

fix help not printed when args missing

---

xbrowse_server/base/management/commands/load_phenotips_from_json.py

Adjusting script to load in PhenoType data from external sources as a

---

xbrowse_server/matchmaker/utilities.py

patient that was matched against incoming query patient in MME that is
in slack alert to #matchmaker_matches channel

minor update to comment styling and fixing a bug with URL path of

---

xbrowse_server/templates/family/family_home.html

requested by Monica ticket #276

making the search in Monarch Initiative optional and driven by the user

---

xbrowse_server/phenotips/views.py

Updating phenotype upload so saving uploaded phenotypes to seqr individual-model as well so the dashboard can see them

Saving uploaded phenotypes to seqr individual model as well so the

---

xbrowse_server/api/utils.py
xbrowse_server/api/views.py
xbrowse_server/staticfiles/js/base/utils.js
xbrowse_server/templates/matchmaker/matchmaker_search_page.html

and also submit this value to MME

Showing the yes|no status of a phenotype HPO term in the upload dialog

---

xbrowse_server/templates/phenotypes/upload_phenotypes.html

Some quick improvements to UI/UX after chatting with Sam
-Spinning wheel/modal to show processing in progress since some of the large uploads takes some time and updating each sample ID with "success" doesn't always clearly get across wip
-Show a better alert when invalid JSON is entered

Feature phenotype upload ui improvements

---

xbrowse_server/templates/reports/project_report.html

the loop has a bug that appends rather than adds to url path

hotfix to adjust a type in a link

---

xbrowse_server/base/management/commands/generate_phenotypes_report.py

command script to generate a report to stdout of phenotypes in seqr

Feature phenotypes report

---

settings.py
xbrowse/core/variant_filters.py
xbrowse/datastore/elasticsearch_datastore.py
xbrowse_server/staticfiles/js/base/select_variants.js
xbrowse_server/templates/client_templates/select_variants.html

allow ac filtering

---

seqr/views/utils/pedigree_info_utils.py
xbrowse_server/base/models.py

1) fix elasticsearch index lookup for family.
2) fix optional bulk upload column handling.

2 bug fixes 

---

settings.py
xbrowse/core/variant_filters.py
xbrowse/datastore/elasticsearch_datastore.py
xbrowse_server/staticfiles/js/base/select_variants.js
xbrowse_server/templates/client_templates/select_variants.html

add hm hemi filters

---

xbrowse_server/templates/client_templates/basic_variant.html

As part of the new saved variants page I updated how we annotate genes so in the old UI you can show gene lists and omim annotations on the relevant gene, instead of ambiguously at the bottom of the list of genes

gene annotations on correct gene

---

deploy/docker/seqr/gcloud/Dockerfile
deploy/docker/seqr/local/Dockerfile

Also, add apt-get --fix-missing arg to avoid apt-get errors on certain packages.

install node and npm to allow UI builds on the dev server. 

---

ui/shared/components/panel/genes/GeneDetail.jsx
ui/shared/components/panel/variants/Annotations.jsx
ui/shared/components/panel/variants/Frequencies.jsx
ui/shared/components/panel/variants/Pathogenicity.jsx
ui/shared/components/panel/variants/VariantGene.jsx
ui/shared/components/panel/variants/VariantLocations.jsx
ui/shared/components/panel/variants/VariantTags.jsx

error message: Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

fix lint error

---

xbrowse_server/base/migrations/0003_auto_20160526_0022.py
xbrowse_server/phenotips/utilities.py
xbrowse_server/phenotips/views.py

When I updated  the new seqr bulk upload not to create phenotps patients and instead create them as needed, I forgot to upload the old xbrowse views to do the same thing

Update xbrowse phenotips to create phenotips patients when needed

---

ui/shared/components/panel/variants/VariantTags.jsx

Added space between username and "on" in _Tagged by_ on hover

Added missing space in VariantTags.jsx

---

xbrowse_server/api/urls.py
xbrowse_server/matchmaker/utilities.py
xbrowse_server/templates/matchmaker/matchmaker_search_page.html

Adjusting url processing to allow for spaces in individual names, and style adjustments for large indeed displays on submission modal

Adjusting url processing to allow for spaces in individual names

---

xbrowse_server/base/utils.py

If a project has some old mongo vcffile objects and some new es ones it may or may not be correctly returned when getting the list of projects in gene search

Correctly determine datastore type for projects in gene search

---

seqr/views/apis/project_api.py

set base_project.genome_version 
add a way to make PhenoTips optional for local installs (though we should probably add  PHENOTIPS_ENABLED, REDIS_ENABLED, etc. variables so these components can be optional for local installs)

set base_project.genome_version. Fixes #692

---

deploy/LOCAL_INSTALL.md
seqr/views/utils/dataset_utils.py
xbrowse/datastore/elasticsearch_datastore.py

Reverts macarthur-lab/seqr#754

Revert "Nested object genotypes"

---

seqr/views/apis/individual_api_tests.py

Added three test cases for the individual apis.

Add ut individual apis

---

seqr/views/apis/case_review_api_tests.py

Added test cases for the case review apis.

Added test cases for the case review apis.

---

seqr/views/apis/auth_api_tests.py

Added three new test cases for the Auth apis.

Add ut auth apis test

---

seqr/views/apis/staff_api_tests.py

A test case for the elasticsearch_status api.

Added a test case for the elasticsearch_status api.

---

seqr/management/commands/add_project_tag_tests.py

The first testcase for testing the normal functionality of the command add_project_tag.

A Seqr management command testcase

---

seqr/views/apis/project_categories_api_tests.py

Added two project categories in the test case to increase coverage.

Add ut project cat apis

---

seqr/management/commands/reload_saved_variant_json.py
seqr/management/commands/reload_saved_variant_json_tests.py

There are two tests for two different command arguments and one for exception test.
This PR also fixed some of unicode issues for the loggings in the command.

Unit tests for Seqr management command reload_saved_variant_json

---

seqr/management/commands/lift_variant_to_hg38_tests.py

There are two cases depending on the user's input.

Added a unit test for lift_variant_to_hg38 command.

---

seqr/management/commands/resend_welcome_email_tests.py

Both normal command and exception tests are included.

Added unit tests for the resend_welcome_email command.

---

seqr/management/commands/copy_project_tags.py

There might be already a good way to do this but I found I often want to copy the tags from one project to another, so I made a simple SeqR management command for that.
Feel free to close if you already have a way to do this but I figured since it's useful for me I'd offer it for what it is worth.

add command to copy tags from one project to another

---

seqr/management/commands/run_postgres_database_backup.py
seqr/management/commands/run_postgres_database_backup_tests.py

Added two test cases and adapted the command code to make the tests work.

Seqr management command unit tests for run_postgres_database_backup

---

reference_data/management/commands/run_reference_data_database_backup.py
reference_data/management/tests/run_reference_data_database_backup_tests.py

Added a unit test for the command run_reference_data_database_backup.

---

seqr/views/apis/staff_api_tests.py

Updated an expected data row of the unit test of discover_sheet API

---

seqr/views/apis/staff_api_tests.py

Added unit tests for sample_metadata_export, saved_variants_page and upload_qc_pipeline_output APIs.

Added unit tests for staff APIs.

---

reference_data/management/tests/update_gencode_tests.py

Unit tests for the reference_data management command update_gencode

---

reference_data/management/commands/utils/download_utils.py
reference_data/management/commands/utils/download_utils_tests.py

Recreates https://github.com/macarthur-lab/seqr/pull/1299 whic was merged without proper approval and reverted.

Unit tests for referenc_data command utils function download_file

---

matchmaker/migrations/0001_initial.py
matchmaker/views/external_api.py
requirements.txt
seqr/migrations/0001_squashed_0067_remove_project_custom_reference_populations.py
seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/middleware.py
seqr/views/apis/case_review_api.py
seqr/views/apis/case_review_api_tests.py
seqr/views/utils/export_utils.py

The file `seqr/utils/middleware.py` is updated because it is called by case_review_api. And its exception handling code is not compatible with Python3.

Converted case_review_api to Py3.

---

reference_data/management/commands/utils/download_utils.py
reference_data/management/commands/utils/download_utils_tests.py

This reverts commit f8da7dd7a7d49cfb5a98e975c41a187269b78d1b.

Revert "Revert "Added unit tests for download_file method.""

---

seqr/management/commands/lift_project_to_hg38.py
seqr/management/tests/lift_project_to_hg38_2_3_tests.py

Changes:
1. `str` literals to `unicode` literals
2. use `list()` for dict `.values()` and `.keys()`
3. change `raw_input()` to `input()`
4. remove `.message` from exceptions
5. change all `int` to 'long int1.

Convert lift_project_to_hg38 command to Python 2 and 3 compatible.

---

seqr/management/commands/run_settings_backup.py
seqr/management/tests/run_settings_backup_2_3_tests.py

Changed the stdout of the command to logging.

Converted run_settings_backup command to be Python 2 and 3 compatible.

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py

Improves test coverage by:
- Removing unused code and refactoring unnecessarily verbose code
- Adding unit tests
- Changing where mocking occurs to allow lower level functionality to be properly tested

Es search unit test coverage

---

seqr/views/apis/users_api.py
seqr/views/apis/users_api_2_3_tests.py

Replaced `urllib` with `requests.utils`.

Converted users_api to Python 2 and 3 compatible.

---

seqr/management/tests/lift_variant_to_hg38_2_3_tests.py
seqr/utils/elasticsearch/es_gene_agg_search.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_2_3_tests.py
seqr/utils/elasticsearch/utils.py
seqr/views/utils/test_utils.py

There are some changes that need to be reviewed and confirmed. Please see the inline comments.

Converted Elasticsearch utils to Python 2 and 3 compatible.

---

matchmaker/matchmaker_utils.py
matchmaker/models.py
matchmaker/views/external_api.py
matchmaker/views/external_api_2_3_tests.py
matchmaker/views/matchmaker_api.py
matchmaker/views/matchmaker_api_2_3_tests.py
seqr/models.py

Some reasons for the changes are inline.

Converted matchmaker apis to Python 2 and 3.

---

seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_2_3_tests.py

Fixes https://github.com/macarthur-lab/seqr-private/issues/871 by updating the server side code for the edit_individuals endpoint to work with the actual data that is sent from the client, and updates the test data to be more representative of the real world data so this bug doesn't happen again

fix edit individuals endpoint

---

seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_tests.py

Fixes https://github.com/macarthur-lab/seqr-private/issues/889

catch errors for missing individuals in bulk upload

---

seqr/utils/elasticsearch/es_search.py

Fixes https://github.com/macarthur-lab/seqr-private/issues/892

fix pagination for recessive search

---

seqr/views/apis/staff_api.py
seqr/views/apis/staff_api_tests.py

Updates the anvil metadata reports based on the requests in https://github.com/macarthur-lab/seqr-private/issues/907 and https://github.com/macarthur-lab/seqr-private/issues/904

Anvil report updates

---

seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py

fix search error

---

deploy/LOCAL_INSTALL.md

Add --genome-version arg to fix dataset loading command.

Fix seqr_loading SeqrMTToESTask command

---

matchmaker/views/external_api.py
matchmaker/views/matchmaker_api.py
seqr/views/apis/analysis_group_api.py
seqr/views/apis/auth_api.py
seqr/views/apis/case_review_api.py
seqr/views/apis/dataset_api.py
seqr/views/apis/family_api.py
seqr/views/apis/gene_api.py
seqr/views/apis/igv_api.py
seqr/views/apis/individual_api.py
seqr/views/apis/locus_list_api.py
seqr/views/apis/project_api.py
seqr/views/apis/project_categories_api.py
seqr/views/apis/saved_variant_api.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/staff_api.py
seqr/views/apis/users_api.py
seqr/views/apis/variant_search_api.py
seqr/views/utils/file_utils.py
settings.py
ui/package-lock.json
ui/package.json
ui/pages/Project/reducers.js
ui/redux/rootReducer.js
ui/shared/components/form/XHRUploaderField.jsx
ui/shared/utils/httpRequestHelper.js

This adds in Django's support for requiring CSRF tokens to be passed on all POST/PUT/DELETE requests

Require csrf

---

seqr/views/apis/staff_api.py
seqr/views/apis/staff_api_tests.py

Updates logic for the download as requested in https://github.com/broadinstitute/seqr-private/issues/921. Does not change the logic for the sample metadata download

update anvil download discovery logic

---

matchmaker/views/external_api.py
matchmaker/views/external_api_tests.py
matchmaker/views/matchmaker_api.py
matchmaker/views/matchmaker_api_tests.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/logging_utils.py
seqr/utils/middleware.py
seqr/utils/redis_utils.py
seqr/utils/redis_utils_tests.py
seqr/views/apis/dataset_api.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/saved_variant_api.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/staff_api.py
seqr/views/apis/staff_api_tests.py
seqr/views/apis/users_api.py
seqr/views/apis/variant_search_api.py
seqr/views/utils/pedigree_info_utils.py
ui/shared/utils/httpRequestHelper.js

We are going to add alerting whenever any errors are logged, so before I do that I wanted to clean up what is logged as an error and what is logged as a warning

Error monitoring

---

ui/pages/Project/constants.js

Adds the sort requested in https://github.com/broadinstitute/seqr/issues/1413

add last analysed sort

---

ui/shared/components/buttons/CreateVariantButton.jsx

Adds functionality to create manual SNVs requested in https://github.com/broadinstitute/seqr-private/issues/926

Manual snv variant

---

seqr/fixtures/new_variant_tag_types.json
seqr/fixtures/variant_tag_types.json

Adds the tag requested in https://github.com/broadinstitute/seqr-private/issues/940

add MNV tag

---

seqr/utils/elasticsearch/es_gene_agg_search.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/utils/logging_utils.py
seqr/views/apis/individual_api_tests.py
seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/pedigree_image_utils.py
seqr/views/utils/pedigree_image_utils_tests.py

Since we now alert on all logged errors, this cleans up some error handling

Error alerting

---

seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/views/apis/dataset_api_tests.py

This fixes https://github.com/broadinstitute/seqr-private/issues/942

only cache full index metadata

---

deploy/kubernetes/postgres/postgres.gcloud.yaml
deploy/kubernetes/seqr/seqr.gcloud.yaml
deploy/kubernetes/shared-settings.yaml
deploy/servctl_utils/deploy_command_utils.py

Creates a new postgres password whenever we deploy secrets

generate postgres password

---

seqr/management/commands/update_mme_contact.py
seqr/management/tests/update_mme_contact_tests.py

Adds a manage command to support the request in https://github.com/broadinstitute/seqr/issues/1512

add update mme contact command

---

matchmaker/views/matchmaker_api.py
matchmaker/views/matchmaker_api_tests.py

fixes https://github.com/broadinstitute/seqr-private/issues/947

fix internal match notes

---

ui/pages/Project/components/CaseReview.jsx

Adds functionality requested in https://github.com/broadinstitute/seqr/issues/1531

make analysis summary editable in case review

---

seqr/views/utils/pedigree_image_utils.py
seqr/views/utils/pedigree_image_utils_tests.py

Fixes https://github.com/broadinstitute/seqr/issues/1530

fix pedigree image generation

---

seqr/utils/elasticsearch/es_search.py

Fixes https://github.com/broadinstitute/seqr/issues/1541

fix bug in variant filtered search

---

deploy/kubernetes/nginx/nginx.yaml

Realized I forgot to add some Ingress annotations as described in https://linkerd.io/2/tasks/using-ingress/#nginx

adds some missing linkerd annotations to the nginx Ingress

---

seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/utils/elasticsearch/utils.py
seqr/utils/middleware.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/test_utils.py

Adds better error handling and error messages for some common search issues

Search error handling

---

matchmaker/views/external_api.py
matchmaker/views/external_api_tests.py
matchmaker/views/matchmaker_api.py
matchmaker/views/matchmaker_api_tests.py
seqr/utils/communication_utils.py

We should fail gracefully and continue normal seqr operation when slack is down

Slack outage handling

---

seqr/views/apis/project_categories_api_tests.py

Fixes flapping test failure from https://travis-ci.org/github/broadinstitute/seqr/jobs/753602007

fix flappy project category test

---

seqr/views/apis/auth_api.py
seqr/views/apis/auth_api_tests.py
seqr/views/react_app.py
seqr/views/react_app_tests.py
seqr/views/utils/terra_api_utils.py

Reverts broadinstitute/seqr#1601

Revert "Added login restrictions to privileged users."

---

seqr/views/apis/project_categories_api_tests.py

Fixes failures like https://travis-ci.org/github/broadinstitute/seqr/jobs/754368203

fix flappy list order in test

---

seqr/fixtures/social_auth.json
seqr/fixtures/users.json
seqr/management/tests/resend_welcome_email_tests.py
seqr/utils/social_auth_pipeline_tests.py
seqr/views/apis/auth_api_tests.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/apis/users_api_tests.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py
seqr/views/utils/test_utils.py

In order to access airtable data confirm users have logged in through google and have Broad email accounts

Airtable auth hardening

---

deploy/kubernetes/elasticsearch/elasticsearch.gcloud.yaml

This sets at the configuration level what I had set via a PUT request while fixing loading. Tested on dev and confirmed this will correctly set the watermark when the config is apllied

update watermark settings for all nodes

---

settings.py

As per suggestion in #1653 .
(cherry picked from commit 33b99f03064db8cd0e37828e7e7d758235babc04)

feat: Parameterised Privacy and TOS version numbers

---

ui/redux/selectors.js
ui/shared/components/graph/IGV.jsx
ui/shared/components/panel/FamilyReads.jsx

Update the UX when multiple sample types are available in IGV

Igv sample types

---

ui/pages/AnvilWorkspace/components/LoadWorkspaceDataForm.jsx
ui/pages/Login/components/Login.jsx
ui/pages/Project/components/ProjectOverview.jsx
ui/shared/utils/constants.js

better validation for the request data form, and adds a link to anvil on the project page

Anvil UI tweaks

---

seqr/views/apis/anvil_workspace_api.py
settings.py

Re-order the validations of the pedigree file and the data path.
And, get the `SERVICE_ACCOUNT_FOR_ANVIL` setting only for AnVIL mode.

Moved parsing pedigree file to the end of validation.

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/terra_api_utils.py
seqr/views/utils/terra_api_utils_tests.py

do not try to validate the file path until the service account had been added

wait for service account access

---

deploy/kubernetes/gcloud-prod-settings.yaml

add terra url to prod

---

seqr/utils/gene_utils.py
seqr/utils/gene_utils_tests.py

Fixes a bug that causes saved variant pages to error and not display anything

correctly handle missing gene sensitivity

---

ui/pages/Project/components/CreateVariantButton.jsx
ui/pages/Project/components/Matchmaker.jsx
ui/pages/Project/components/SavedVariants.jsx
ui/pages/Project/components/SelectSavedVariantsTable.jsx
ui/pages/Project/constants.js
ui/pages/Project/selectors.js
ui/shared/components/table/DataTable.jsx

Creates a user interface to tag multiple existing saved variant together

Link variants UI

---

ui/package-lock.json
ui/package.json
ui/shared/components/panel/view-fields/TextFieldView.jsx
ui/shared/utils/stringUtils.js

The library we were using for rendering markdown hasn't been updated in 4 years and is insecure, so switching to something thats more current

Update markdown renderer

---

seqr/views/apis/superuser_api.py
seqr/views/apis/superuser_api_tests.py
ui/pages/DataManagement/components/Users.jsx
ui/shared/components/table/DataTable.jsx

This will allow us to easily monitor the progress of getting all our users to log in with oauth

Add Oauth column to users table

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py

Fixes bugs introduced in https://github.com/broadinstitute/seqr/pull/1867/files

fix predictor sorts for keyword types

---

seqr/fixtures/report_variants.json
seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
ui/pages/Report/constants.js

It seems that the "discovery_note" logic should work for both UI and AnVIL Report. The changes in this draft PR are for AnVIL Report only.

Added discovery_notes column.

---

ui/shared/components/icons/PedigreeIcon.jsx

Due to our CSP policies the style wasn't being applied

fix pedigree icon style

---

ui/shared/components/panel/FamilyReads.jsx

The changes are in the constant `REFERENCE_TRACKS` and then regenerated the static files.

Changed the options for the IGV reference tracks to improve IGV performance.

---

ui/shared/components/panel/variants/VariantIndividuals.jsx

The layout of an example miss matching case:

Added CN and call type miss match warning.

---

seqr/migrations/0024_varianttag_metadata.py

May not be applicable to upstream but creating as reference for others.  These changes were required for our environment.
(cherry picked from commit 5051882c8f3395df8bc90dfcb00436742cfbacb0)

fix: Use SeqrLogger in DB migration

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/auth_api.py
seqr/views/utils/permissions_utils.py
seqr/views/utils/test_utils.py
settings.py

Enforce that users accept policies in order to access anvil-specific pages

Anvil accept policies

---

ui/pages/Project/components/CaseReview.jsx
ui/pages/Project/components/FamilyPage.jsx
ui/pages/Project/components/FamilyTable/CaseReviewStatusDropdown.jsx
ui/pages/Project/components/FamilyTable/FamilyTable.jsx
ui/pages/Project/components/FamilyTable/header/TableHeaderRow.jsx
ui/pages/Project/components/ProjectOverview.jsx
ui/pages/Project/components/ProjectPageUI.jsx
ui/pages/Project/components/SavedVariants.jsx
ui/pages/Project/components/edit-families-and-individuals/BulkEditForm.jsx
ui/pages/Project/constants.js
ui/pages/Project/selectors.js
ui/pages/Project/selectors.test.js
ui/pages/SummaryData/components/SavedVariants.jsx
ui/redux/selectors.js
ui/shared/components/buttons/ExportTableButton.jsx
ui/shared/components/form/BulkUploadForm.jsx
ui/shared/components/form/StateChangeForm.jsx
ui/shared/components/graph/HorizontalStackedBar.jsx
ui/shared/components/panel/FamilyReads.jsx
ui/shared/components/panel/family.jsx
ui/shared/components/panel/genes/LocusListDetail.jsx
ui/shared/components/panel/variants/FamilyVariantTags.jsx
ui/shared/components/panel/variants/SavedVariants.jsx
ui/shared/components/panel/variants/selectors.js
ui/shared/components/panel/view-fields/TextFieldView.jsx
ui/shared/components/table/DataTable.jsx
ui/shared/utils/constants.js

A variety of changes that speed up the react rendering time, mainly on the project pages. For RGP, reduces the initial JS rendering time from ~23 seconds to ~8 seconds

Performance improvements

---

seqr/utils/file_utils.py
seqr/utils/file_utils_tests.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/utils/file_utils.py
settings.py

It is a draft PR because the unit tests haven't been fully updated.

Updated for AnVIL loading pipeline improvement.

---

ui/pages/Project/components/FamilyTable/header/TableHeaderRow.jsx
ui/shared/components/panel/family/Family.jsx
ui/shared/utils/constants.js

No functional changes to this PR, but cleans up constants so their usage is clearer. Will make an upcoming PR I'm working on easier to read

clean up family render field constants

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py

the seqr account authenticated for searching in ES does not (and should not!) have sufficient permission to cancel long running searches. Instead, log an error so we are notified if this is happening

log error for long running tasks

---

reference_data/management/commands/update_omim.py
reference_data/management/commands/utils/update_utils.py
reference_data/management/tests/test_utils.py
reference_data/management/tests/update_omim_tests.py

adds resiliency and alerting if updating omim reference data fails

Omim update stability

---

ui/shared/components/form/Inputs.jsx
ui/shared/components/panel/family/FamilyReads.jsx

It implements part of issue # 1032. The RNA-seq reference tracks come in later PR.

Split the DNA/RNA tracks.

---

seqr/views/apis/igv_api.py
seqr/views/apis/igv_api_tests.py

Changed the fixed token expiration time to one fetched from Google.

Added getting token expiry before caching it.

---

seqr/fixtures/1kg_project.json
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/apis/saved_variant_api.py
seqr/views/apis/saved_variant_api_tests.py
seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/orm_to_json_utils.py
ui/pages/Project/components/RnaSeqOutliers.jsx
ui/pages/Project/reducers.js
ui/pages/Project/selectors.js
ui/redux/rootReducer.js
ui/redux/selectors.js
ui/shared/components/panel/fixtures.js
ui/shared/components/panel/variants/FamilyVariantTags.jsx
ui/shared/components/panel/variants/VariantGene.jsx
ui/shared/components/panel/variants/VariantGene.test.js

Builds off of https://github.com/broadinstitute/seqr/pull/2345 to add a flag on genes in variants that have outlier RNA seq

Rna-seq outlier search result gene flag

---

seqr/management/commands/load_rna_seq.py
seqr/management/tests/load_rna_seq_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/dataset_utils.py

The file upload is too big to upload via the UI in production, so creating a manage command.

create manage command for loading rna seq

---

README.md

Add guidance for external code contributions to our README

add code contribution guidelines

---

ui/pages/Project/components/GeneLists.jsx
ui/redux/selectors.js
ui/shared/components/table/LocusListTables.jsx

The feature request is to be able to hit "enter" to add a gene list. Forms automatically submit when you hit enter, so refactoring this to actually be a form

Select gene list on enter

---

seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
seqr/views/apis/variant_search_api.py
seqr/views/utils/project_context_utils.py

This is another " no changed functionality" PR. Takes a utility function that has a conditional option to do lots of extra stuff, and moves the extra stuff into the one file that actually needs it

move child entity code to search file

---

seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py

Excel has a column limit that we run into when we try to export too many families per variant

Fix excel export for many families

---

ui/shared/components/form/FormWrapper.jsx

This fixes the bug where you can't change the search form filters after submitting

reset from submission state on external change

---

ui/pages/Project/components/GeneLists.jsx
ui/shared/components/form/FormHelpers.jsx
ui/shared/components/table/DataTable.jsx

This does not necessarily solve the underlying issue of the linked ticket (I am still trying to replicate the bug) but adds a better user experience for adding gene lists and showing if somehow no lists have been selected

add locus list validation

---

seqr/utils/elasticsearch/constants.py

Updates size sort to sort translocations between other Svs and SNPs

translocation size sort

---

ui/shared/utils/constants.js

For issue https://github.com/broadinstitute/seqr/issues/2605

Fix spelling error

---

ui/pages/Project/components/FamilyTable/FamilyTable.jsx

Keep the number of cells in the tbody and tfoot equal

---

deploy/kubectl_helpers/utils/copy.sh

No ticket, but the way the quoting works currently does not actually allow this command to run

fix kubectl copy helper

---

ui/shared/utils/localStorage.js

[seqr #2637](https://github.com/broadinstitute/seqr/issues/2637)

clear local storage on save error

---

deploy/servctl_utils/deploy_command_utils.py

Adds a new secret we need to `deploy_command_utils`

add airflow secret to deploy helper

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

If the dag is running, the triggering process will fail.

Check if AnVIL DAGs are running

---

ui/shared/components/form/FormWrapper.jsx

Fixes https://github.com/broadinstitute/seqr/issues/2711

fix form error formatting when no error body

---

seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/utils/test_utils.py

Fixes the issue in https://github.com/broadinstitute/seqr/issues/2725

Fix clinvar override for comp het pairs

---

ui/shared/components/panel/variants/VariantGene.jsx

Updates behavior per https://github.com/broadinstitute/seqr/issues/2727

Locus list max height

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py
seqr/views/utils/airtable_utils.py
settings.py

This PR does not change any functionality, it just abstracts out code for accessing airtable that will be needed for https://github.com/broadinstitute/seqr-private/issues/1147 . Making this its own PR makes understanding the diff for that PR easier, and also it adds a bit of test coverage to make sure no inadvertent changes happen.

Airtable helper class

---

ui/shared/components/panel/family/FamilyLayout.jsx
ui/shared/components/panel/variants/Annotations.jsx

Fixes some errors that show in the browser console when react is rendering

fix browser console errors

---

ui/shared/components/panel/variants/VariantIndividuals.jsx

Add a `comment` field to the mito cn entry in the `GENOTYPE_DETAIL`. Update the `formattedGenotypeDetails` to show the comment.
The screenshot is as below picture.

Add a comment to mito CN.

---

seqr/views/apis/awesomebar_api.py

This refactors the code for the awesomebar to move the formatting of results into the db layer using Django's `values` functions. This will be useful for https://github.com/broadinstitute/seqr/issues/1976 as it means that formatting and more importantly sorting can be pushed to the db layer instead of needing to post process results. This does not change behavior

Awesomebar refactor

---

seqr/utils/redis_utils.py
seqr/views/status.py
seqr/views/utils/variant_utils.py
settings.py

Hi,
I'm working on getting seqr running on our HPC with singularity instead of docker. For this it was necessary to be able to configure all ports dynamically, so I have added a REDIS_SERVICE_PORT setting.

add REDIS_SERVICE_PORT to settings

---

seqr/views/apis/summary_data_api.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/project_context_utils.py
seqr/views/utils/variant_utils.py

When checking that I had not drpped coverage on a recent PR, I discovered that there is a bunch of unreachable cod eint eh orm_to_json_utils file, so this cleans that up

Clean up unused fucntionality

---

seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py

Change the version to a timestamp in the `project_path` attribute of the data loading DAG.

Change the version to ts in the project_path of the DAG.

---

ui/shared/components/panel/variants/Annotations.jsx

This adds a couple of links to variants, and also cleans up the code for generating that list of links as it was hard to work with

Pop db links

---

seqr/urls.py
seqr/views/apis/igv_api.py
seqr/views/apis/igv_api_tests.py
ui/shared/components/panel/family/constants.js

Use the latest Broad hg38 reference file for IGV

Igv reference file update

---

seqr/utils/elasticsearch/es_search.py

This does not change any functionality but changes the es utils code to rely more on attributes like `self._consequence_overrides` and less on passing around variables. This will make it much easier for my upcoming PR, but I want to review the actual functionality differences separate from this refactor

Es utils override cleanup

---

seqr/urls.py
seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
ui/pages/Project/components/ProjectCollaborators.jsx
ui/pages/Project/fixtures.js
ui/pages/Project/reducers.js
ui/pages/Project/selectors.js

fetching collaborators from anvil is sometimes slow, there is no reason to hold up the rest of the page while waiting for it

Collaborator loading optimization

---

deploy/kubectl_helpers/restore_local_db.sh

Update the seqr temp bucket for db backup.

---

seqr/utils/elasticsearch/constants.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/utils/test_utils.py
ui/shared/components/panel/search/constants.js

See this [ticket](https://github.com/broadinstitute/seqr/issues/2005) for details.

Add homozygote count for the SNP `this callset` .

---

seqr/fixtures/1kg_project.json
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/family_api_tests.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/variant_utils.py
ui/pages/Project/components/PhenotypePrioritizedGenes.jsx

See this [ticket](https://github.com/broadinstitute/seqr/issues/3110) for details.

Show top 10 ranked phenotype prioritized genes

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py
seqr/views/utils/test_utils.py
ui/shared/utils/constants.js

The display for the gnomAD AN and AC, new gene consequence:
The new search annotation for the structural consequences:

Add new SV data format support.

---

ui/pages/Project/components/PhenotypePrioritizedGenes.jsx
ui/shared/components/buttons/SearchResultsLink.jsx

Add LIRICAL frequency filter

---

seqr/management/tests/load_rna_seq_outlier_tests.py
seqr/models.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/case_review_api.py
seqr/views/apis/case_review_api_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/apis/family_api.py
seqr/views/apis/individual_api.py
seqr/views/apis/individual_api_tests.py
seqr/views/apis/project_api.py
seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/individual_utils.py
seqr/views/utils/orm_to_json_utils.py
seqr/views/utils/orm_to_json_utils_tests.py
seqr/views/utils/project_context_utils.py
seqr/views/utils/test_utils.py
seqr/views/utils/variant_utils.py
ui/shared/components/buttons/SearchResultsLink.jsx

This changes out several usages of `_get_json_for_models` to the more efficient `get_json_for_queryset`

Queryset json performance

---

settings.py
ui/shared/components/panel/variants/ClinGenVciLink.jsx

Change the API URL from http to https.

Change ClinGen Allele Registry API URL to HTTPS.

---

ui/pages/Project/constants.js

Moves constants with no other changes to make follow up PR more readable

fix constant ordering

---

seqr/utils/communication_utils.py
seqr/views/apis/project_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/utils/pedigree_info_utils_tests.py
seqr/views/utils/project_context_utils.py

Not sure how these were able to make it past Codacy, but here we are

remove unused imports

---

seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py

For 20,000+ row file, speeds up response time from 80 seconds to 10 seconds

External analysis - fix 504

---

panelapp/pa_locus_list_api_tests.py
seqr/views/apis/case_review_api_tests.py
seqr/views/apis/locus_list_api_tests.py

Adds hlper functions and shared base class to remove unit test code duplication

Codacy dupliction fixes

---

seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/dataset_utils.py

Fix RNAseq data loading SQL syntax error.

---

seqr/management/commands/lift_project_to_hg38.py
seqr/management/tests/lift_project_to_hg38_tests.py
seqr/views/apis/dataset_api.py
seqr/views/utils/dataset_utils.py

No functionality change, but splits apart the sample matching functionality, so we can update the RNA functionality without further diverging from the searching functionality

Split sample matching functionality

---

seqr/views/apis/data_manager_api_tests.py

This PR creates a common test function for basic loading tests to prepare it for adding more data loading tests.

Create a common test function for basic loading tests.

---

seqr/views/utils/dataset_utils.py

This is the refactor I proposed in my last PR review. It would allow us to create an explicit mapping from samples to individual-project combinations.

helper functions for call-specific individual sample individual lookup

---

ui/pages/Report/components/Anvil.jsx
ui/shared/components/page/ProjectSelector.jsx

This moves existing behavior for selecting a project from the awesomebar and updating a component and makes it reusable, will be needed for a upcoming PR

abstract project selector component

---

seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/individual_api_tests.py
seqr/views/utils/pedigree_info_utils.py
seqr/views/utils/pedigree_info_utils_tests.py

Cleans up loading for pedigree files to support upcoming changes to validation. Also changes validation to report all errors in the file instead of only the first error

Pedigree loading cleanup

---

requirements.txt

fixes the snyk error on the release PR

Bump vulnerable redis

---

seqr/utils/elasticsearch/es_search.py
seqr/utils/elasticsearch/es_utils_tests.py

We are returning an invalid selected transcript ID in one particular edge case. We had a unit test for that case so our coverage was at 100% but we did not actually check that the outputted variants were formatted correctly so we missed the bug

fix selected transcript for multi dataset comp het

---

seqr/management/commands/lift_project_to_hg38.py
seqr/management/commands/lift_variant_to_hg38.py
seqr/utils/middleware.py
seqr/utils/search/elasticsearch/constants.py
seqr/utils/search/elasticsearch/es_gene_agg_search.py
seqr/utils/search/elasticsearch/es_search.py
seqr/utils/search/elasticsearch/es_utils_tests.py
seqr/utils/search/utils.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
seqr/views/status.py
seqr/views/utils/dataset_utils.py
seqr/views/utils/variant_utils.py

This moves without changing the elasticsearch code into a nested folder, to support adding the new hail backend search

move es utils into nested folder

---

deploy/LOCAL_INSTALL.md

Requested in https://github.com/broadinstitute/seqr/discussions/3370#discussioncomment-5909334

update local install readme to explain updating reference data

---

seqr/views/apis/summary_data_api.py
seqr/views/apis/summary_data_api_tests.py
ui/pages/Search/components/PageHeader.jsx
ui/pages/Search/selectors.js
ui/pages/SummaryData/components/Hpo.jsx

Shortens the URL by grouping families by project, and fixes search by having build-specific links

HPO summary search fix

---

seqr/utils/search/elasticsearch/es_search.py
seqr/utils/search/elasticsearch/es_utils_tests.py

We no longer index the `contig` field and can not search against it in new indices

use xpos for X-linked filtering

---

CHANGELOG.md
seqr/urls.py
seqr/utils/vcf_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/airflow_utils.py
seqr/views/utils/test_utils.py
settings.py
ui/pages/DataManagement/DataManagement.jsx
ui/pages/DataManagement/components/LoadData.jsx
ui/shared/components/StateDataLoader.jsx
ui/shared/components/form/FormWizard.jsx
ui/shared/components/form/Inputs.jsx
ui/shared/components/form/LoadOptionsSelect.jsx
ui/shared/components/page/Header.jsx
ui/shared/components/panel/LoadWorkspaceDataForm.jsx

This creates a interface to trigger internal data loading. This involved refactoring existing code from the anvil workspace API to make it sharable, and also involved refactoring those tests to make a sharable TestCase for that as well. This also uses the FormWizard UI component for the workflow, and in using that I also made some changes to make that easier to share

Load Data UI for PMs

---

ui/shared/components/panel/variants/Annotations.jsx

The v3 pipeline handles some of the formatting for the lof fields from VEP, and we should support both v2 and v3 in the UI

update LOF display for v3 pipeline

---

seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/airflow_utils.py

Getting an error when triggering loading on a DAG the first time its run

handle error for first loading time dag is triggered

---

seqr/management/tests/load_rna_seq_tpm_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/dataset_utils.py

Allow TPM value to be zero.

---

seqr/utils/search/elasticsearch/es_search.py
seqr/utils/search/elasticsearch/es_utils_tests.py

Fix SV localtion interval filter bug.

---

.github/workflows/unit-tests.yml
hail_search/test_search.py
hail_search/test_utils.py
seqr/utils/search/hail_search_utils_tests.py

moves constants and helper method for hail search tests into the hail search folder

shared utilities for hail backend tests

---

ui/shared/components/panel/variants/Predictions.jsx
ui/shared/utils/constants.js

New in-silico thresholds

---

hail_search/queries/base.py
hail_search/queries/mito.py
hail_search/test_search.py

Adds new search behavior into hail backend

Hail backend - noncoding exon canonical transcript

---

seqr/views/apis/report_api.py
seqr/views/utils/airtable_utils.py
seqr/views/utils/anvil_metadata_utils.py
seqr/views/utils/variant_utils.py

As part of https://github.com/broadinstitute/seqr/issues/3612 we need to move a lot of code into shared utilities files. This PR only copies things around with no changes, except to change function names where necessary

move anvil metadata utilities to utils files

---

deploy/docker/seqr/Dockerfile

Dev docker build is broken due to recent changes.  We need to:
- nest the copied directories.
- add a few files from the root.

fix docker build

---

deploy/LOCAL_DEVELOPMENT_INSTALL.md
deploy/kubectl_helpers/restore_local_db.sh
settings.py

I got local seqr running and hit a few small things.

Local dev run-through changes

---

.github/workflows/hail-search-unit-tests.yaml
.github/workflows/unit-tests.yml

Opening this pr should also provide a test of itself!

Missing paths filter in GitHub actions.

---

ui/shared/components/panel/variants/Annotations.jsx

linting error is causing the npm build step in the docker build to fail

fix npm build

---

deploy/docker/seqr/entrypoint.sh

bam/crams job has finally succeeded!

Remove crons from app

---

deploy/docker/seqr/entrypoint.sh
settings.py

Service account is now enabled via workload identity (at least on dev!)

Remove dependency on service account key

---

hail_search/queries/base.py
hail_search/queries/multi_data_types.py

Fixes some miscellaneous bugs with SV search in the hail backend and improves performance

Hail backend - SV comp het fixes

---

seqr/views/apis/report_api.py
seqr/views/utils/anvil_metadata_utils.py
seqr/views/utils/variant_utils.py
seqr/views/utils/variant_utils_tests.py

the logic for this function was really convoluted and there were a few uncovered branches. This simplifies the logic which fixes the bug and also hopefully makes it more resilient

simplify control flow for variant inheritance

---

ui/pages/SummaryData/SummaryData.jsx

Was erroring with 
```
pages/SummaryData/SummaryData.jsx
Line 18:8:  Using exported name 'SampleMetadata' as identifier for default export  import/no-named-as-default
```

fix linting error

---

seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/airflow_utils.py

fix file path for moving loading files to gs

---

seqr/views/utils/airflow_utils.py

Fixes test flaps such as https://github.com/broadinstitute/seqr/actions/runs/7202070469/job/19619494846?pr=3784

prevent test flap failure

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/search/add_data_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/dataset_api_tests.py
seqr/views/apis/project_api.py
seqr/views/apis/project_api_tests.py
seqr/views/utils/airtable_utils.py
seqr/views/utils/test_utils.py

Updates the anvil loading tracker when data is added to a project and when a project is deleted

Anvil tracking update

---

seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py
seqr/utils/search/utils.py

Do not allow unrestricted searches across large SNV/Indel projects

Restrict no location hail backend search

---

seqr/views/apis/individual_api_tests.py
seqr/views/utils/pedigree_info_utils.py

Fixes issues in the latest samplle manifest upload

Sample manifest bug

---

seqr/views/utils/dataset_utils.py

fixes a bug/inefficiency introduced in my last PR, and also reformats a confusing helper function

rna seq parsing clean up

---

hail_search/queries/base.py
hail_search/queries/sv.py
hail_search/test_search.py
seqr/utils/search/hail_search_utils.py
seqr/utils/search/hail_search_utils_tests.py

We were previously looking up matching SVs with a different sample type by just checking if there is any overlap between them. In fact, we should be checking that the breakpoints are within a specified tolerance of each other
Comparable ES functionality: https://github.com/broadinstitute/seqr/blob/master/seqr/utils/search/elasticsearch/es_search.py#L1427

Sv lookup interval

---

hail_search/queries/mito.py

Changed a Mendiliome search that failed locally after 500 seconds to finishing in 90 seconds 🤷‍♀️

improve performance for search with many intervals

---

hail_search/queries/base.py

I have now run the needed timing requests on dev, so we should revert this

Undo timing

---

seqr/management/commands/load_rna_seq.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/dataset_utils.py

Improves performance for loading RNA data by streaming directly to sample files

Rna seq loading performance

---

ui/pages/Login/components/SetPassword.jsx

We switched the JS library we use for handling forms like a couple years ago and the old library accepted an array of validators and the new one doesn't :shrug:

fix set password form validation

---

seqr/views/apis/variant_search_api.py
seqr/views/apis/variant_search_api_tests.py
ui/pages/Report/components/CustomSearch.jsx

add trio only option to custom search

---

ui/pages/Project/components/CreateVariantButton.jsx
ui/pages/Project/components/FamilyPage.jsx

add gene field to manual sv form

---

settings.py

example of a discussion post with an image:
without this code change, image will not render and this error is printed to the console:

allow images from github discussions for feature updates page

---

ui/pages/Project/components/SavedVariants.jsx

This will prevent the use error that caused the bug in the linked ticket

add validation for comp het pairs in same gene in link variants UI

---

seqr/admin.py

I forgot to add the new model to the django admin

add dynamic analysis group to django admin

---

ui/pages/DataManagement/components/RnaSeq.jsx

add link to upload format document for rna-seq

---

panelapp/pa_locus_list_api_tests.py
panelapp/panelapp_utils.py
requirements.in
requirements.txt

I chose to add tenacity as opposed to using urllib3.util.Retry because it's simper to use and is also well supported, lots of stars on github

add tenacity retry to panelapp function

---

panelapp/pa_locus_list_api_tests.py
panelapp/panelapp_utils.py

_get_all_genes() is recursive so putting the retry decorator on that function probably caused the RecursionError. I moved the retry decorator to wrap the GET request only.

panelapp retry GET request only

---

.github/workflows/dev-hail-search-release.yaml
.github/workflows/dev-release.yaml

The location of the seqr dev values.yaml file changed when we merged  https://github.com/broadinstitute/tgg-helm/pull/82

update image tags in dev-broad-seqr chart

---

ui/shared/components/panel/variants/Annotations.jsx

https://ncbi.nlm.nih.gov/research/litvar2/docsum?variant=litvar@CA116312%23rs121907892%23%23&query=CA116312

add LitVar2 link

---

ui/shared/components/panel/variants/selectors.js
ui/shared/utils/constants.js

The saved variant download was never updated to work with the new hail backend variant fields

fix formatting for saved variant download

---

seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/airflow_utils.py
seqr/views/utils/test_utils.py

Airflow PR: https://github.com/broadinstitute/seqr-pipeline-airflow/pull/253

Support only a single callset path

---

seqr/utils/middleware.py
seqr/views/utils/terra_api_utils_tests.py
seqr/views/utils/test_utils.py
settings.py

Reverts broadinstitute/seqr#4228

Revert "add custom middleware to log csrf request info"

---

seqr/utils/search/add_data_utils.py
seqr/views/apis/anvil_workspace_api.py
seqr/views/apis/anvil_workspace_api_tests.py
seqr/views/apis/data_manager_api.py
seqr/views/utils/airflow_utils.py

This abstracts out some code that will need to be shared for the local loading UI. Everything is just copy-pasted without changes to simplify review

split shared helper function into beter utils file

---

seqr/management/commands/check_for_new_samples_from_pipeline.py
seqr/management/tests/check_for_new_samples_from_pipeline_tests.py

PR to add the file path to metadata: https://github.com/broadinstitute/seqr-loading-pipelines/pull/935

add relatedness check tsv to failure message

---

seqr/views/utils/airtable_utils.py

Does not fix Dan's issue with loading, but means that if this happens in the future he will get a more useful error and can work it out directly with the PMS

add human-readable error for misconfigured PDO

---

reference_data/management/commands/update_all_reference_data.py
reference_data/management/commands/update_gencode_latest.py
reference_data/management/commands/utils/update_utils.py
reference_data/management/tests/update_all_reference_data_tests.py
reference_data/management/tests/update_omim_tests.py

I statrted this when I though I needed to refactor the update reference data job. i don;t for now, but this is still better than what we currently have so worth merging

Reference data handler cleanup

---

seqr/views/apis/data_manager_api.py
seqr/views/utils/airtable_utils.py

Improves on https://github.com/broadinstitute/seqr/pull/4480 to catch some additional error cases

Pdo missing project error

---

seqr/views/apis/report_api.py
seqr/views/apis/report_api_tests.py

Adds better errors and warnings when data is missing from airtable for the gregor reports

Better gregor missing airtable warnings

---

vlm/test_vlm.py
vlm/web_app.py

Updates VLM route to work with ingress routing

add vlm route prefix

---

test_local_deployment.sh

https://github.com/broadinstitute/seqr/pull/4505 failed to update the local install test so it is failing, this will fix the issue

update local install test

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/views/utils/airtable_utils.py

If we can not identify an expected single airtable record to update we should send a slack to alert people instead of logging an error

send slack notification on failed airtabe record update

---

seqr/management/commands/check_for_new_samples_from_pipeline.py

I had lowered this as a quick test to see if it would fix the performance issues and forgot to raise it back

increase lookup chunk size

---

seqr/views/utils/airflow_utils.py
seqr/views/utils/test_utils.py

Addresses: https://github.com/broadinstitute/seqr-private/issues/1568

bugfix: airflow api request for in progress DAG.

---

matchmaker/views/external_api_tests.py
seqr/models.py
seqr/utils/search/add_data_utils.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/family_api.py
seqr/views/apis/igv_api.py
seqr/views/apis/project_api.py
seqr/views/apis/report_api.py
seqr/views/apis/summary_data_api.py
seqr/views/utils/dataset_utils.py
seqr/views/utils/orm_to_json_utils_tests.py
seqr/views/utils/variant_utils.py

We try never to merge PRs that are failing codacy but over time stuff sneaks through. This cleans up all out current errors, which hopefully means in subsequent PRs you won't get stuck with an existing error blocking your PR

Fix outstanding codacy errors

---

seqr/views/react_app.py
seqr/views/react_app_tests.py
ui/app.html

when pulling gogogle analytics for this years seqr update I realized we would have way better data if we tracked the user

track user in google analytics

---

seqr/management/tests/check_for_new_samples_from_pipeline_tests.py
seqr/utils/search/hail_search_utils.py

This should fix the flappiness in the reload annotation jobs

Retry multi lookup

---

seqr/utils/vcf_utils.py

From user report: https://github.com/broadinstitute/seqr-helm/issues/104

bugfix: handle bytes returned from dd

---

seqr/views/apis/family_api.py
seqr/views/apis/family_api_tests.py

The UI was updated buut the backend was not 🤷

correctly allow for external anvil family deletion

---

clickhouse_search/search.py
seqr/urls.py
seqr/views/apis/data_manager_api.py
seqr/views/apis/data_manager_api_tests.py
seqr/views/utils/test_utils.py
ui/pages/DataManagement/DataManagement.jsx
ui/pages/DataManagement/components/TriggerDagPages.jsx
ui/pages/DataManagement/components/TriggerSearchDataUpdatePages.jsx

Adds the functionality to delete search data for a project. Refactors the generic "trigger dag" functionality to make it more specific and removes references to DAGs from the UI code entirely

Delete project in clickhouse

---

.github/workflows/vlm-unit-tests.yaml
vlm/clickhouse_utils.py

Need to better namespace env vars to work with shared secrets

update clickhouse env vars

---

.github/workflows/unit-tests.yml
deploy/docker/seqr/Dockerfile

I think these are the only changes needed

python 3.11
